FROM ghcr.io/cirruslabs/flutter:stable AS builder
WORKDIR /app

COPY pubspec.yaml pubspec.lock ./
COPY packages/merope_ads/pubspec.yaml packages/merope_ads/pubspec.yaml
COPY packages/merope_core/pubspec.yaml packages/merope_core/pubspec.yaml
COPY packages/merope_models/pubspec.yaml packages/merope_models/pubspec.yaml
COPY packages/merope_ui/pubspec.yaml packages/merope_ui/pubspec.yaml
RUN flutter pub get

COPY . .
RUN flutter analyze --no-fatal-infos --no-fatal-warnings
RUN flutter build web --release

FROM nginx:1.27-alpine
COPY --from=builder /app/build/web /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
