// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AdAccount struct {
	ID               pgtype.UUID        `json:"id"`
	TenantID         pgtype.UUID        `json:"tenant_id"`
	UserID           pgtype.UUID        `json:"user_id"`
	BillingProfileID pgtype.Text        `json:"billing_profile_id"`
	Status           string             `json:"status"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type AdClick struct {
	ID             pgtype.UUID        `json:"id"`
	ImpressionID   pgtype.UUID        `json:"impression_id"`
	CreativeID     pgtype.UUID        `json:"creative_id"`
	ClickTimestamp pgtype.Timestamptz `json:"click_timestamp"`
	RedirectUrl    string             `json:"redirect_url"`
	IsFraud        bool               `json:"is_fraud"`
}

type AdConversion struct {
	ID                  pgtype.UUID        `json:"id"`
	ClickID             pgtype.UUID        `json:"click_id"`
	ConversionType      string             `json:"conversion_type"`
	Value               int32              `json:"value"`
	Currency            string             `json:"currency"`
	ConversionTimestamp pgtype.Timestamptz `json:"conversion_timestamp"`
}

type AdGroup struct {
	ID          pgtype.UUID        `json:"id"`
	CampaignID  pgtype.UUID        `json:"campaign_id"`
	Name        string             `json:"name"`
	BidStrategy string             `json:"bid_strategy"`
	BidAmount   int32              `json:"bid_amount"`
	Pacing      string             `json:"pacing"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type AdImpression struct {
	ID           pgtype.UUID        `json:"id"`
	AuctionLogID pgtype.UUID        `json:"auction_log_id"`
	CreativeID   pgtype.UUID        `json:"creative_id"`
	PlacementID  pgtype.UUID        `json:"placement_id"`
	PublisherID  pgtype.UUID        `json:"publisher_id"`
	AdvertiserID pgtype.UUID        `json:"advertiser_id"`
	CampaignID   pgtype.UUID        `json:"campaign_id"`
	AdGroupID    pgtype.UUID        `json:"ad_group_id"`
	UserHash     string             `json:"user_hash"`
	IpHash       string             `json:"ip_hash"`
	UaHash       pgtype.Text        `json:"ua_hash"`
	Timestamp    pgtype.Timestamptz `json:"timestamp"`
}

type AdPlacement struct {
	ID                 pgtype.UUID        `json:"id"`
	PublisherAccountID pgtype.UUID        `json:"publisher_account_id"`
	SiteID             pgtype.UUID        `json:"site_id"`
	Name               string             `json:"name"`
	Type               string             `json:"type"`
	FloorPriceCpm      int32              `json:"floor_price_cpm"`
	AdRulesJson        []byte             `json:"ad_rules_json"`
	Status             string             `json:"status"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type AdTag struct {
	ID          pgtype.UUID        `json:"id"`
	PlacementID pgtype.UUID        `json:"placement_id"`
	TagCode     string             `json:"tag_code"`
	TagType     string             `json:"tag_type"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type AppStoreListing struct {
	ID          pgtype.UUID        `json:"id"`
	AppID       pgtype.UUID        `json:"app_id"`
	Description pgtype.Text        `json:"description"`
	IconUrl     pgtype.Text        `json:"icon_url"`
	Category    pgtype.Text        `json:"category"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type AuctionLog struct {
	ID               pgtype.UUID        `json:"id"`
	PlacementID      pgtype.UUID        `json:"placement_id"`
	UserSegment      string             `json:"user_segment"`
	WinnerCreativeID pgtype.UUID        `json:"winner_creative_id"`
	WinPriceCpm      int32              `json:"win_price_cpm"`
	Timestamp        pgtype.Timestamptz `json:"timestamp"`
}

type Audience struct {
	ID            pgtype.UUID        `json:"id"`
	AdAccountID   pgtype.UUID        `json:"ad_account_id"`
	Name          string             `json:"name"`
	TargetingJson []byte             `json:"targeting_json"`
	Status        string             `json:"status"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Bid struct {
	ID        pgtype.UUID        `json:"id"`
	AdGroupID pgtype.UUID        `json:"ad_group_id"`
	BidType   string             `json:"bid_type"`
	BidAmount int32              `json:"bid_amount"`
	MaxSpend  int32              `json:"max_spend"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Block struct {
	BlockerID pgtype.UUID        `json:"blocker_id"`
	BlockedID pgtype.UUID        `json:"blocked_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type BotWebhook struct {
	ID          pgtype.UUID        `json:"id"`
	BotID       pgtype.UUID        `json:"bot_id"`
	CallbackUrl string             `json:"callback_url"`
	Events      []string           `json:"events"`
	SecretToken string             `json:"secret_token"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Broadcast struct {
	ID          pgtype.UUID        `json:"id"`
	HostID      pgtype.UUID        `json:"host_id"`
	Title       string             `json:"title"`
	ViewerCount int32              `json:"viewer_count"`
	IsLive      bool               `json:"is_live"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	EndedAt     pgtype.Timestamptz `json:"ended_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type BusinessProfile struct {
	UserID             pgtype.UUID        `json:"user_id"`
	Category           string             `json:"category"`
	ContactEmail       pgtype.Text        `json:"contact_email"`
	Website            pgtype.Text        `json:"website"`
	Address            pgtype.Text        `json:"address"`
	IsVerifiedBusiness bool               `json:"is_verified_business"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type Campaign struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	AdAccountID pgtype.UUID        `json:"ad_account_id"`
	Name        string             `json:"name"`
	Objective   string             `json:"objective"`
	BudgetTotal int32              `json:"budget_total"`
	BudgetDaily int32              `json:"budget_daily"`
	StartAt     pgtype.Timestamptz `json:"start_at"`
	EndAt       pgtype.Timestamptz `json:"end_at"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type ChatMember struct {
	RoomID   pgtype.UUID        `json:"room_id"`
	UserID   pgtype.UUID        `json:"user_id"`
	Role     string             `json:"role"`
	JoinedAt pgtype.Timestamptz `json:"joined_at"`
}

type ChatMessage struct {
	ID              pgtype.UUID        `json:"id"`
	RoomID          pgtype.UUID        `json:"room_id"`
	AuthorID        pgtype.UUID        `json:"author_id"`
	ParentID        pgtype.UUID        `json:"parent_id"`
	ForwardedFromID pgtype.UUID        `json:"forwarded_from_id"`
	Content         string             `json:"content"`
	MessageType     string             `json:"message_type"`
	VoiceUrl        pgtype.Text        `json:"voice_url"`
	IsEdited        bool               `json:"is_edited"`
	IsPinned        bool               `json:"is_pinned"`
	IsEncrypted     bool               `json:"is_encrypted"`
	Version         int32              `json:"version"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type ChatMessageRead struct {
	MessageID pgtype.UUID        `json:"message_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	ReadAt    pgtype.Timestamptz `json:"read_at"`
}

type ChatRoom struct {
	ID        pgtype.UUID        `json:"id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	Name      pgtype.Text        `json:"name"`
	IsGroup   bool               `json:"is_group"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Circle struct {
	ID        pgtype.UUID        `json:"id"`
	OwnerID   pgtype.UUID        `json:"owner_id"`
	Name      string             `json:"name"`
	IsPrivate bool               `json:"is_private"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type CircleMember struct {
	CircleID pgtype.UUID        `json:"circle_id"`
	UserID   pgtype.UUID        `json:"user_id"`
	Role     string             `json:"role"`
	JoinedAt pgtype.Timestamptz `json:"joined_at"`
}

type Comment struct {
	ID        pgtype.UUID        `json:"id"`
	PostID    pgtype.UUID        `json:"post_id"`
	AuthorID  pgtype.UUID        `json:"author_id"`
	ParentID  pgtype.UUID        `json:"parent_id"`
	Content   string             `json:"content"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Community struct {
	ID             pgtype.UUID        `json:"id"`
	TenantID       pgtype.UUID        `json:"tenant_id"`
	OwnerID        pgtype.UUID        `json:"owner_id"`
	Name           string             `json:"name"`
	Description    pgtype.Text        `json:"description"`
	AvatarUrl      pgtype.Text        `json:"avatar_url"`
	Bylaws         pgtype.Text        `json:"bylaws"`
	GovernanceType string             `json:"governance_type"`
	IsPrivate      bool               `json:"is_private"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type CommunityMember struct {
	CommunityID pgtype.UUID        `json:"community_id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Role        string             `json:"role"`
	JoinedAt    pgtype.Timestamptz `json:"joined_at"`
}

type CommunityProposal struct {
	ID          pgtype.UUID        `json:"id"`
	CommunityID pgtype.UUID        `json:"community_id"`
	ProposerID  pgtype.UUID        `json:"proposer_id"`
	Title       string             `json:"title"`
	Description string             `json:"description"`
	Status      string             `json:"status"`
	EndsAt      pgtype.Timestamptz `json:"ends_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Creative struct {
	ID               pgtype.UUID        `json:"id"`
	AdGroupID        pgtype.UUID        `json:"ad_group_id"`
	Name             string             `json:"name"`
	Type             string             `json:"type"`
	MediaUrl         string             `json:"media_url"`
	ContentText      pgtype.Text        `json:"content_text"`
	CtaText          pgtype.Text        `json:"cta_text"`
	LandingUrl       string             `json:"landing_url"`
	Status           string             `json:"status"`
	ComplianceStatus string             `json:"compliance_status"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type DeveloperApp struct {
	ID           pgtype.UUID        `json:"id"`
	OwnerID      pgtype.UUID        `json:"owner_id"`
	Name         string             `json:"name"`
	ClientID     string             `json:"client_id"`
	ClientSecret string             `json:"client_secret"`
	RedirectUri  pgtype.Text        `json:"redirect_uri"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type EnergyDrop struct {
	ID          pgtype.UUID        `json:"id"`
	BroadcastID pgtype.UUID        `json:"broadcast_id"`
	SenderID    pgtype.UUID        `json:"sender_id"`
	Amount      int32              `json:"amount"`
	DropType    string             `json:"drop_type"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type EscrowRecord struct {
	ID          pgtype.UUID        `json:"id"`
	OrderID     pgtype.UUID        `json:"order_id"`
	BuyerID     pgtype.UUID        `json:"buyer_id"`
	SellerID    pgtype.UUID        `json:"seller_id"`
	Amount      int32              `json:"amount"`
	Status      string             `json:"status"`
	Description pgtype.Text        `json:"description"`
	ReleaseAt   pgtype.Timestamptz `json:"release_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Event struct {
	ID           pgtype.UUID        `json:"id"`
	CommunityID  pgtype.UUID        `json:"community_id"`
	CreatorID    pgtype.UUID        `json:"creator_id"`
	Title        string             `json:"title"`
	Description  pgtype.Text        `json:"description"`
	StartsAt     pgtype.Timestamptz `json:"starts_at"`
	EndsAt       pgtype.Timestamptz `json:"ends_at"`
	LocationName pgtype.Text        `json:"location_name"`
	Status       string             `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type EventAttendee struct {
	EventID pgtype.UUID        `json:"event_id"`
	UserID  pgtype.UUID        `json:"user_id"`
	Status  string             `json:"status"`
	RsvpAt  pgtype.Timestamptz `json:"rsvp_at"`
}

type FeatureFlag struct {
	ID                pgtype.UUID        `json:"id"`
	TenantID          pgtype.UUID        `json:"tenant_id"`
	Key               string             `json:"key"`
	IsEnabled         bool               `json:"is_enabled"`
	RolloutPercentage int32              `json:"rollout_percentage"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type Follow struct {
	FollowerID  pgtype.UUID        `json:"follower_id"`
	FollowingID pgtype.UUID        `json:"following_id"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type FollowRequest struct {
	FollowerID  pgtype.UUID        `json:"follower_id"`
	FollowingID pgtype.UUID        `json:"following_id"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Hashtag struct {
	ID        pgtype.UUID        `json:"id"`
	Tag       string             `json:"tag"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type IdentityKey struct {
	UserID    pgtype.UUID        `json:"user_id"`
	DeviceID  string             `json:"device_id"`
	PublicKey []byte             `json:"public_key"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type InstalledApp struct {
	UserID      pgtype.UUID        `json:"user_id"`
	AppID       pgtype.UUID        `json:"app_id"`
	Permissions []string           `json:"permissions"`
	InstalledAt pgtype.Timestamptz `json:"installed_at"`
}

type LegacyContact struct {
	UserID              pgtype.UUID        `json:"user_id"`
	ContactUserID       pgtype.UUID        `json:"contact_user_id"`
	AccessType          string             `json:"access_type"`
	TriggerDaysInactive int32              `json:"trigger_days_inactive"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

type MediaTree struct {
	ID           pgtype.UUID        `json:"id"`
	ParentPostID pgtype.UUID        `json:"parent_post_id"`
	ChildPostID  pgtype.UUID        `json:"child_post_id"`
	RemixType    string             `json:"remix_type"`
	Metadata     []byte             `json:"metadata"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Mention struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	EntityType string             `json:"entity_type"`
	EntityID   pgtype.UUID        `json:"entity_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Notification struct {
	ID           pgtype.UUID        `json:"id"`
	ReceiverID   pgtype.UUID        `json:"receiver_id"`
	SenderID     pgtype.UUID        `json:"sender_id"`
	Type         string             `json:"type"`
	EntityType   string             `json:"entity_type"`
	EntityID     pgtype.UUID        `json:"entity_id"`
	IsRead       bool               `json:"is_read"`
	GroupedCount int32              `json:"grouped_count"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type OnetimePrekey struct {
	ID        int32              `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	DeviceID  string             `json:"device_id"`
	KeyID     int32              `json:"key_id"`
	PublicKey []byte             `json:"public_key"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Order struct {
	ID              pgtype.UUID        `json:"id"`
	BuyerID         pgtype.UUID        `json:"buyer_id"`
	TotalAmount     int32              `json:"total_amount"`
	Status          string             `json:"status"`
	ShippingAddress pgtype.Text        `json:"shipping_address"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type OrderItem struct {
	ID              pgtype.UUID `json:"id"`
	OrderID         pgtype.UUID `json:"order_id"`
	ProductID       pgtype.UUID `json:"product_id"`
	Quantity        int32       `json:"quantity"`
	PriceAtPurchase int32       `json:"price_at_purchase"`
}

type Payout struct {
	ID                 pgtype.UUID        `json:"id"`
	PublisherAccountID pgtype.UUID        `json:"publisher_account_id"`
	PlacementID        pgtype.UUID        `json:"placement_id"`
	Date               pgtype.Timestamptz `json:"date"`
	Impressions        int32              `json:"impressions"`
	Revenue            int32              `json:"revenue"`
	Currency           string             `json:"currency"`
	Status             string             `json:"status"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type Poll struct {
	ID        pgtype.UUID        `json:"id"`
	PostID    pgtype.UUID        `json:"post_id"`
	Question  string             `json:"question"`
	EndsAt    pgtype.Timestamptz `json:"ends_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type PollOption struct {
	ID         pgtype.UUID `json:"id"`
	PollID     pgtype.UUID `json:"poll_id"`
	OptionText string      `json:"option_text"`
}

type PollVote struct {
	PollID    pgtype.UUID        `json:"poll_id"`
	OptionID  pgtype.UUID        `json:"option_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Post struct {
	ID               pgtype.UUID        `json:"id"`
	TenantID         pgtype.UUID        `json:"tenant_id"`
	AuthorID         pgtype.UUID        `json:"author_id"`
	CoAuthorID       pgtype.UUID        `json:"co_author_id"`
	ContentText      string             `json:"content_text"`
	MediaUrls        []string           `json:"media_urls"`
	Visibility       string             `json:"visibility"`
	IsLocked         bool               `json:"is_locked"`
	IsPinned         bool               `json:"is_pinned"`
	IsArchived       bool               `json:"is_archived"`
	IsDraft          bool               `json:"is_draft"`
	LocationName     pgtype.Text        `json:"location_name"`
	Latitude         pgtype.Float8      `json:"latitude"`
	Longitude        pgtype.Float8      `json:"longitude"`
	ContentWarning   pgtype.Text        `json:"content_warning"`
	UnlockPrice      pgtype.Int4        `json:"unlock_price"`
	DigitalSignature pgtype.Text        `json:"digital_signature"`
	PublicKeyID      pgtype.Text        `json:"public_key_id"`
	PublishedAt      pgtype.Timestamptz `json:"published_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type PostHashtag struct {
	PostID    pgtype.UUID `json:"post_id"`
	HashtagID pgtype.UUID `json:"hashtag_id"`
}

type Product struct {
	ID            pgtype.UUID        `json:"id"`
	SellerID      pgtype.UUID        `json:"seller_id"`
	Name          string             `json:"name"`
	Description   pgtype.Text        `json:"description"`
	Price         int32              `json:"price"`
	Currency      string             `json:"currency"`
	StockQuantity int32              `json:"stock_quantity"`
	Category      string             `json:"category"`
	MediaUrls     []string           `json:"media_urls"`
	IsDigital     bool               `json:"is_digital"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type PublisherAccount struct {
	ID              pgtype.UUID        `json:"id"`
	TenantID        pgtype.UUID        `json:"tenant_id"`
	UserID          pgtype.UUID        `json:"user_id"`
	PayoutProfileID pgtype.Text        `json:"payout_profile_id"`
	Status          string             `json:"status"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type Reaction struct {
	ID           pgtype.UUID        `json:"id"`
	UserID       pgtype.UUID        `json:"user_id"`
	TargetID     pgtype.UUID        `json:"target_id"`
	ReactionType string             `json:"reaction_type"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Report struct {
	ID         pgtype.UUID        `json:"id"`
	ReporterID pgtype.UUID        `json:"reporter_id"`
	TargetType string             `json:"target_type"`
	TargetID   pgtype.UUID        `json:"target_id"`
	Reason     string             `json:"reason"`
	Status     string             `json:"status"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type SearchHistory struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Query     string             `json:"query"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type SearchInterest struct {
	UserID    pgtype.UUID        `json:"user_id"`
	Interest  string             `json:"interest"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Session struct {
	ID           pgtype.UUID        `json:"id"`
	UserID       pgtype.UUID        `json:"user_id"`
	DeviceID     string             `json:"device_id"`
	IpAddress    string             `json:"ip_address"`
	Latitude     pgtype.Float8      `json:"latitude"`
	Longitude    pgtype.Float8      `json:"longitude"`
	City         pgtype.Text        `json:"city"`
	Country      pgtype.Text        `json:"country"`
	UserAgent    string             `json:"user_agent"`
	IsActive     bool               `json:"is_active"`
	IsGhostMode  bool               `json:"is_ghost_mode"`
	LastActiveAt pgtype.Timestamptz `json:"last_active_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type SignedPrekey struct {
	ID        int32              `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	DeviceID  string             `json:"device_id"`
	KeyID     int32              `json:"key_id"`
	PublicKey []byte             `json:"public_key"`
	Signature []byte             `json:"signature"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Site struct {
	ID            pgtype.UUID        `json:"id"`
	TenantID      pgtype.UUID        `json:"tenant_id"`
	PublisherID   pgtype.UUID        `json:"publisher_id"`
	Name          string             `json:"name"`
	Url           string             `json:"url"`
	ContentRating string             `json:"content_rating"`
	Status        string             `json:"status"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type SparkMatch struct {
	ID        pgtype.UUID        `json:"id"`
	UserAID   pgtype.UUID        `json:"user_a_id"`
	UserBID   pgtype.UUID        `json:"user_b_id"`
	Score     float64            `json:"score"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type SpendRecord struct {
	ID          pgtype.UUID `json:"id"`
	AdAccountID pgtype.UUID `json:"ad_account_id"`
	CampaignID  pgtype.UUID `json:"campaign_id"`
	AdGroupID   pgtype.UUID `json:"ad_group_id"`
	Date        pgtype.Date `json:"date"`
	Impressions int32       `json:"impressions"`
	Clicks      int32       `json:"clicks"`
	Spend       int32       `json:"spend"`
	Currency    string      `json:"currency"`
}

type Story struct {
	ID         pgtype.UUID        `json:"id"`
	AuthorID   pgtype.UUID        `json:"author_id"`
	MediaUrl   string             `json:"media_url"`
	MediaType  string             `json:"media_type"`
	IsArchived bool               `json:"is_archived"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type StoryHighlight struct {
	ID        pgtype.UUID        `json:"id"`
	AuthorID  pgtype.UUID        `json:"author_id"`
	Name      string             `json:"name"`
	CoverUrl  pgtype.Text        `json:"cover_url"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type StoryHighlightItem struct {
	HighlightID pgtype.UUID `json:"highlight_id"`
	StoryID     pgtype.UUID `json:"story_id"`
}

type StoryView struct {
	StoryID  pgtype.UUID        `json:"story_id"`
	UserID   pgtype.UUID        `json:"user_id"`
	ViewedAt pgtype.Timestamptz `json:"viewed_at"`
}

type Subscription struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Plan      string             `json:"plan"`
	StartedAt pgtype.Timestamptz `json:"started_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	Active    bool               `json:"active"`
}

type Tenant struct {
	ID           pgtype.UUID        `json:"id"`
	Name         string             `json:"name"`
	Domain       string             `json:"domain"`
	CustomConfig []byte             `json:"custom_config"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Transaction struct {
	ID        pgtype.UUID        `json:"id"`
	WalletID  pgtype.UUID        `json:"wallet_id"`
	Amount    pgtype.Numeric     `json:"amount"`
	Currency  string             `json:"currency"`
	Type      string             `json:"type"`
	Reference pgtype.Text        `json:"reference"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID                  pgtype.UUID        `json:"id"`
	TenantID            pgtype.UUID        `json:"tenant_id"`
	Username            string             `json:"username"`
	DisplayName         pgtype.Text        `json:"display_name"`
	Bio                 pgtype.Text        `json:"bio"`
	Email               string             `json:"email"`
	PasswordHash        string             `json:"password_hash"`
	AvatarUrl           pgtype.Text        `json:"avatar_url"`
	IsVerified          bool               `json:"is_verified"`
	MfaEnabled          bool               `json:"mfa_enabled"`
	MfaSecret           pgtype.Text        `json:"mfa_secret"`
	LastSeenAt          pgtype.Timestamptz `json:"last_seen_at"`
	IsOnline            bool               `json:"is_online"`
	IsPrivate           bool               `json:"is_private"`
	ProfileLock         bool               `json:"profile_lock"`
	FailedLoginAttempts int32              `json:"failed_login_attempts"`
	LockedUntil         pgtype.Timestamptz `json:"locked_until"`
	ThemeConfig         []byte             `json:"theme_config"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type UserLocation struct {
	UserID      pgtype.UUID        `json:"user_id"`
	Location    interface{}        `json:"location"`
	IsGhostMode bool               `json:"is_ghost_mode"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type VaultItem struct {
	ID            pgtype.UUID        `json:"id"`
	UserID        pgtype.UUID        `json:"user_id"`
	Title         string             `json:"title"`
	EncryptedData string             `json:"encrypted_data"`
	ItemType      string             `json:"item_type"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type VideoHotspot struct {
	ID               pgtype.UUID        `json:"id"`
	PostID           pgtype.UUID        `json:"post_id"`
	TimestampSeconds float64            `json:"timestamp_seconds"`
	CoordX           float64            `json:"coord_x"`
	CoordY           float64            `json:"coord_y"`
	ActionType       string             `json:"action_type"`
	ActionPayload    []byte             `json:"action_payload"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type VideoMetadatum struct {
	PostID           pgtype.UUID   `json:"post_id"`
	DurationSeconds  int32         `json:"duration_seconds"`
	ResolutionWidth  pgtype.Int4   `json:"resolution_width"`
	ResolutionHeight pgtype.Int4   `json:"resolution_height"`
	EncodingStatus   string        `json:"encoding_status"`
	IsSpatial        bool          `json:"is_spatial"`
	SpatialConfig    []byte        `json:"spatial_config"`
	BitrateKbps      pgtype.Int4   `json:"bitrate_kbps"`
	FrameRate        pgtype.Float8 `json:"frame_rate"`
}

type VideoTrack struct {
	ID           pgtype.UUID        `json:"id"`
	PostID       pgtype.UUID        `json:"post_id"`
	TrackType    string             `json:"track_type"`
	LanguageCode string             `json:"language_code"`
	MediaUrl     string             `json:"media_url"`
	IsOriginal   bool               `json:"is_original"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Wallet struct {
	UserID    pgtype.UUID        `json:"user_id"`
	Balance   int32              `json:"balance"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type WatchHubSession struct {
	ID                 pgtype.UUID        `json:"id"`
	RoomID             pgtype.UUID        `json:"room_id"`
	CurrentPostID      pgtype.UUID        `json:"current_post_id"`
	ModeratorID        pgtype.UUID        `json:"moderator_id"`
	PlaybackState      string             `json:"playback_state"`
	CurrentTimeSeconds float64            `json:"current_time_seconds"`
	LastSyncAt         pgtype.Timestamptz `json:"last_sync_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}
