// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addChatMember = `-- name: AddChatMember :exec
INSERT INTO chat_members (room_id, user_id, role) VALUES ($1, $2, $3)
`

type AddChatMemberParams struct {
	RoomID pgtype.UUID `json:"room_id"`
	UserID pgtype.UUID `json:"user_id"`
	Role   string      `json:"role"`
}

func (q *Queries) AddChatMember(ctx context.Context, arg AddChatMemberParams) error {
	_, err := q.db.Exec(ctx, addChatMember, arg.RoomID, arg.UserID, arg.Role)
	return err
}

const addEnergyDrop = `-- name: AddEnergyDrop :one
INSERT INTO energy_drops (broadcast_id, sender_id, amount, drop_type) VALUES ($1, $2, $3, $4)
RETURNING id, broadcast_id, sender_id, amount, drop_type, created_at
`

type AddEnergyDropParams struct {
	BroadcastID pgtype.UUID `json:"broadcast_id"`
	SenderID    pgtype.UUID `json:"sender_id"`
	Amount      int32       `json:"amount"`
	DropType    string      `json:"drop_type"`
}

func (q *Queries) AddEnergyDrop(ctx context.Context, arg AddEnergyDropParams) (EnergyDrop, error) {
	row := q.db.QueryRow(ctx, addEnergyDrop,
		arg.BroadcastID,
		arg.SenderID,
		arg.Amount,
		arg.DropType,
	)
	var i EnergyDrop
	err := row.Scan(
		&i.ID,
		&i.BroadcastID,
		&i.SenderID,
		&i.Amount,
		&i.DropType,
		&i.CreatedAt,
	)
	return i, err
}

const addInterest = `-- name: AddInterest :exec
INSERT INTO search_interests (user_id, interest) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddInterestParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	Interest string      `json:"interest"`
}

func (q *Queries) AddInterest(ctx context.Context, arg AddInterestParams) error {
	_, err := q.db.Exec(ctx, addInterest, arg.UserID, arg.Interest)
	return err
}

const addOrderItem = `-- name: AddOrderItem :exec
INSERT INTO order_items (order_id, product_id, quantity, price_at_purchase)
VALUES ($1, $2, $3, $4)
`

type AddOrderItemParams struct {
	OrderID         pgtype.UUID `json:"order_id"`
	ProductID       pgtype.UUID `json:"product_id"`
	Quantity        int32       `json:"quantity"`
	PriceAtPurchase int32       `json:"price_at_purchase"`
}

func (q *Queries) AddOrderItem(ctx context.Context, arg AddOrderItemParams) error {
	_, err := q.db.Exec(ctx, addOrderItem,
		arg.OrderID,
		arg.ProductID,
		arg.Quantity,
		arg.PriceAtPurchase,
	)
	return err
}

const addReaction = `-- name: AddReaction :one
INSERT INTO reactions (user_id, target_id, reaction_type)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, target_id) DO UPDATE SET reaction_type = EXCLUDED.reaction_type
RETURNING id, user_id, target_id, reaction_type, created_at
`

type AddReactionParams struct {
	UserID       pgtype.UUID `json:"user_id"`
	TargetID     pgtype.UUID `json:"target_id"`
	ReactionType string      `json:"reaction_type"`
}

func (q *Queries) AddReaction(ctx context.Context, arg AddReactionParams) (Reaction, error) {
	row := q.db.QueryRow(ctx, addReaction, arg.UserID, arg.TargetID, arg.ReactionType)
	var i Reaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TargetID,
		&i.ReactionType,
		&i.CreatedAt,
	)
	return i, err
}

const addVaultItem = `-- name: AddVaultItem :one
INSERT INTO vault_items (user_id, title, encrypted_data, item_type) VALUES ($1, $2, $3, $4)
RETURNING id, user_id, title, encrypted_data, item_type, created_at
`

type AddVaultItemParams struct {
	UserID        pgtype.UUID `json:"user_id"`
	Title         string      `json:"title"`
	EncryptedData string      `json:"encrypted_data"`
	ItemType      string      `json:"item_type"`
}

type AddVaultItemRow struct {
	ID            pgtype.UUID        `json:"id"`
	UserID        pgtype.UUID        `json:"user_id"`
	Title         string             `json:"title"`
	EncryptedData string             `json:"encrypted_data"`
	ItemType      string             `json:"item_type"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

// 13. Vault
func (q *Queries) AddVaultItem(ctx context.Context, arg AddVaultItemParams) (AddVaultItemRow, error) {
	row := q.db.QueryRow(ctx, addVaultItem,
		arg.UserID,
		arg.Title,
		arg.EncryptedData,
		arg.ItemType,
	)
	var i AddVaultItemRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.EncryptedData,
		&i.ItemType,
		&i.CreatedAt,
	)
	return i, err
}

const addVideoHotspot = `-- name: AddVideoHotspot :one
INSERT INTO video_hotspots (post_id, timestamp_seconds, coord_x, coord_y, action_type, action_payload)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, post_id, timestamp_seconds, coord_x, coord_y, action_type, action_payload, created_at
`

type AddVideoHotspotParams struct {
	PostID           pgtype.UUID `json:"post_id"`
	TimestampSeconds float64     `json:"timestamp_seconds"`
	CoordX           float64     `json:"coord_x"`
	CoordY           float64     `json:"coord_y"`
	ActionType       string      `json:"action_type"`
	ActionPayload    []byte      `json:"action_payload"`
}

func (q *Queries) AddVideoHotspot(ctx context.Context, arg AddVideoHotspotParams) (VideoHotspot, error) {
	row := q.db.QueryRow(ctx, addVideoHotspot,
		arg.PostID,
		arg.TimestampSeconds,
		arg.CoordX,
		arg.CoordY,
		arg.ActionType,
		arg.ActionPayload,
	)
	var i VideoHotspot
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.TimestampSeconds,
		&i.CoordX,
		&i.CoordY,
		&i.ActionType,
		&i.ActionPayload,
		&i.CreatedAt,
	)
	return i, err
}

const addVideoTrack = `-- name: AddVideoTrack :one
INSERT INTO video_tracks (post_id, track_type, language_code, media_url)
VALUES ($1, $2, $3, $4)
RETURNING id, post_id, track_type, language_code, media_url, is_original, created_at
`

type AddVideoTrackParams struct {
	PostID       pgtype.UUID `json:"post_id"`
	TrackType    string      `json:"track_type"`
	LanguageCode string      `json:"language_code"`
	MediaUrl     string      `json:"media_url"`
}

func (q *Queries) AddVideoTrack(ctx context.Context, arg AddVideoTrackParams) (VideoTrack, error) {
	row := q.db.QueryRow(ctx, addVideoTrack,
		arg.PostID,
		arg.TrackType,
		arg.LanguageCode,
		arg.MediaUrl,
	)
	var i VideoTrack
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.TrackType,
		&i.LanguageCode,
		&i.MediaUrl,
		&i.IsOriginal,
		&i.CreatedAt,
	)
	return i, err
}

const blockUser = `-- name: BlockUser :exec
INSERT INTO blocks (blocker_id, blocked_id) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type BlockUserParams struct {
	BlockerID pgtype.UUID `json:"blocker_id"`
	BlockedID pgtype.UUID `json:"blocked_id"`
}

// 22. Blocks
func (q *Queries) BlockUser(ctx context.Context, arg BlockUserParams) error {
	_, err := q.db.Exec(ctx, blockUser, arg.BlockerID, arg.BlockedID)
	return err
}

const castPollVote = `-- name: CastPollVote :exec
INSERT INTO poll_votes (poll_id, option_id, user_id) VALUES ($1, $2, $3)
ON CONFLICT (poll_id, user_id) DO UPDATE SET option_id = EXCLUDED.option_id
`

type CastPollVoteParams struct {
	PollID   pgtype.UUID `json:"poll_id"`
	OptionID pgtype.UUID `json:"option_id"`
	UserID   pgtype.UUID `json:"user_id"`
}

func (q *Queries) CastPollVote(ctx context.Context, arg CastPollVoteParams) error {
	_, err := q.db.Exec(ctx, castPollVote, arg.PollID, arg.OptionID, arg.UserID)
	return err
}

const createBotWebhook = `-- name: CreateBotWebhook :one
INSERT INTO bot_webhooks (bot_id, callback_url, events, secret_token)
VALUES ($1, $2, $3, $4)
RETURNING id, bot_id, callback_url, events, secret_token, created_at
`

type CreateBotWebhookParams struct {
	BotID       pgtype.UUID `json:"bot_id"`
	CallbackUrl string      `json:"callback_url"`
	Events      []string    `json:"events"`
	SecretToken string      `json:"secret_token"`
}

func (q *Queries) CreateBotWebhook(ctx context.Context, arg CreateBotWebhookParams) (BotWebhook, error) {
	row := q.db.QueryRow(ctx, createBotWebhook,
		arg.BotID,
		arg.CallbackUrl,
		arg.Events,
		arg.SecretToken,
	)
	var i BotWebhook
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.CallbackUrl,
		&i.Events,
		&i.SecretToken,
		&i.CreatedAt,
	)
	return i, err
}

const createBroadcast = `-- name: CreateBroadcast :one
INSERT INTO broadcasts (host_id, title, is_live) VALUES ($1, $2, $3)
RETURNING id, host_id, title, viewer_count, is_live, started_at, created_at
`

type CreateBroadcastParams struct {
	HostID pgtype.UUID `json:"host_id"`
	Title  string      `json:"title"`
	IsLive bool        `json:"is_live"`
}

type CreateBroadcastRow struct {
	ID          pgtype.UUID        `json:"id"`
	HostID      pgtype.UUID        `json:"host_id"`
	Title       string             `json:"title"`
	ViewerCount int32              `json:"viewer_count"`
	IsLive      bool               `json:"is_live"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

// 30. Lumia Broadcasting
func (q *Queries) CreateBroadcast(ctx context.Context, arg CreateBroadcastParams) (CreateBroadcastRow, error) {
	row := q.db.QueryRow(ctx, createBroadcast, arg.HostID, arg.Title, arg.IsLive)
	var i CreateBroadcastRow
	err := row.Scan(
		&i.ID,
		&i.HostID,
		&i.Title,
		&i.ViewerCount,
		&i.IsLive,
		&i.StartedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createChatMessage = `-- name: CreateChatMessage :one
INSERT INTO chat_messages (room_id, author_id, parent_id, content, message_type, voice_url, is_encrypted)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, room_id, author_id, parent_id, forwarded_from_id, content, message_type, voice_url, is_edited, is_pinned, is_encrypted, version, created_at, updated_at
`

type CreateChatMessageParams struct {
	RoomID      pgtype.UUID `json:"room_id"`
	AuthorID    pgtype.UUID `json:"author_id"`
	ParentID    pgtype.UUID `json:"parent_id"`
	Content     string      `json:"content"`
	MessageType string      `json:"message_type"`
	VoiceUrl    pgtype.Text `json:"voice_url"`
	IsEncrypted bool        `json:"is_encrypted"`
}

func (q *Queries) CreateChatMessage(ctx context.Context, arg CreateChatMessageParams) (ChatMessage, error) {
	row := q.db.QueryRow(ctx, createChatMessage,
		arg.RoomID,
		arg.AuthorID,
		arg.ParentID,
		arg.Content,
		arg.MessageType,
		arg.VoiceUrl,
		arg.IsEncrypted,
	)
	var i ChatMessage
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.AuthorID,
		&i.ParentID,
		&i.ForwardedFromID,
		&i.Content,
		&i.MessageType,
		&i.VoiceUrl,
		&i.IsEdited,
		&i.IsPinned,
		&i.IsEncrypted,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createChatRoom = `-- name: CreateChatRoom :one
INSERT INTO chat_rooms (name, is_group) VALUES ($1, $2) RETURNING id, tenant_id, name, is_group, created_at
`

type CreateChatRoomParams struct {
	Name    pgtype.Text `json:"name"`
	IsGroup bool        `json:"is_group"`
}

// 8. Messaging
func (q *Queries) CreateChatRoom(ctx context.Context, arg CreateChatRoomParams) (ChatRoom, error) {
	row := q.db.QueryRow(ctx, createChatRoom, arg.Name, arg.IsGroup)
	var i ChatRoom
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.IsGroup,
		&i.CreatedAt,
	)
	return i, err
}

const createComment = `-- name: CreateComment :one
INSERT INTO comments (post_id, author_id, parent_id, content)
VALUES ($1, $2, $3, $4)
RETURNING id, post_id, author_id, parent_id, content, created_at, updated_at
`

type CreateCommentParams struct {
	PostID   pgtype.UUID `json:"post_id"`
	AuthorID pgtype.UUID `json:"author_id"`
	ParentID pgtype.UUID `json:"parent_id"`
	Content  string      `json:"content"`
}

// 6. Comments & Reactions
func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, createComment,
		arg.PostID,
		arg.AuthorID,
		arg.ParentID,
		arg.Content,
	)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.AuthorID,
		&i.ParentID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCommunity = `-- name: CreateCommunity :one
INSERT INTO communities (owner_id, name, description, avatar_url, is_private)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, owner_id, name, description, avatar_url, bylaws, governance_type, is_private, created_at
`

type CreateCommunityParams struct {
	OwnerID     pgtype.UUID `json:"owner_id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	AvatarUrl   pgtype.Text `json:"avatar_url"`
	IsPrivate   bool        `json:"is_private"`
}

// 10. Communities & Events
func (q *Queries) CreateCommunity(ctx context.Context, arg CreateCommunityParams) (Community, error) {
	row := q.db.QueryRow(ctx, createCommunity,
		arg.OwnerID,
		arg.Name,
		arg.Description,
		arg.AvatarUrl,
		arg.IsPrivate,
	)
	var i Community
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.AvatarUrl,
		&i.Bylaws,
		&i.GovernanceType,
		&i.IsPrivate,
		&i.CreatedAt,
	)
	return i, err
}

const createDeveloperApp = `-- name: CreateDeveloperApp :one
INSERT INTO developer_apps (owner_id, name, client_id, client_secret)
VALUES ($1, $2, $3, $4)
RETURNING id, owner_id, name, client_id, client_secret, redirect_uri, created_at
`

type CreateDeveloperAppParams struct {
	OwnerID      pgtype.UUID `json:"owner_id"`
	Name         string      `json:"name"`
	ClientID     string      `json:"client_id"`
	ClientSecret string      `json:"client_secret"`
}

// 14. Developer & Apps
func (q *Queries) CreateDeveloperApp(ctx context.Context, arg CreateDeveloperAppParams) (DeveloperApp, error) {
	row := q.db.QueryRow(ctx, createDeveloperApp,
		arg.OwnerID,
		arg.Name,
		arg.ClientID,
		arg.ClientSecret,
	)
	var i DeveloperApp
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.ClientID,
		&i.ClientSecret,
		&i.RedirectUri,
		&i.CreatedAt,
	)
	return i, err
}

const createEscrowRecord = `-- name: CreateEscrowRecord :one
INSERT INTO escrow_records (order_id, buyer_id, seller_id, amount, status, description, release_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, order_id, buyer_id, seller_id, amount, status, description, release_at, created_at
`

type CreateEscrowRecordParams struct {
	OrderID     pgtype.UUID        `json:"order_id"`
	BuyerID     pgtype.UUID        `json:"buyer_id"`
	SellerID    pgtype.UUID        `json:"seller_id"`
	Amount      int32              `json:"amount"`
	Status      string             `json:"status"`
	Description pgtype.Text        `json:"description"`
	ReleaseAt   pgtype.Timestamptz `json:"release_at"`
}

// 12. Escrow
func (q *Queries) CreateEscrowRecord(ctx context.Context, arg CreateEscrowRecordParams) (EscrowRecord, error) {
	row := q.db.QueryRow(ctx, createEscrowRecord,
		arg.OrderID,
		arg.BuyerID,
		arg.SellerID,
		arg.Amount,
		arg.Status,
		arg.Description,
		arg.ReleaseAt,
	)
	var i EscrowRecord
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.BuyerID,
		&i.SellerID,
		&i.Amount,
		&i.Status,
		&i.Description,
		&i.ReleaseAt,
		&i.CreatedAt,
	)
	return i, err
}

const createEvent = `-- name: CreateEvent :one
INSERT INTO community_proposals (community_id, proposer_id, title, description, ends_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, community_id, proposer_id, title, description, status, ends_at, created_at
`

type CreateEventParams struct {
	CommunityID pgtype.UUID        `json:"community_id"`
	ProposerID  pgtype.UUID        `json:"proposer_id"`
	Title       string             `json:"title"`
	Description string             `json:"description"`
	EndsAt      pgtype.Timestamptz `json:"ends_at"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (CommunityProposal, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.CommunityID,
		arg.ProposerID,
		arg.Title,
		arg.Description,
		arg.EndsAt,
	)
	var i CommunityProposal
	err := row.Scan(
		&i.ID,
		&i.CommunityID,
		&i.ProposerID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.EndsAt,
		&i.CreatedAt,
	)
	return i, err
}

const createEventTicket = `-- name: CreateEventTicket :one
INSERT INTO transactions (wallet_id, amount, currency, type, reference) VALUES ($1, 0, 'TRY', 'event_ticket', $2)
RETURNING id, wallet_id, amount, currency, type, reference, status, created_at
`

type CreateEventTicketParams struct {
	WalletID  pgtype.UUID `json:"wallet_id"`
	Reference pgtype.Text `json:"reference"`
}

func (q *Queries) CreateEventTicket(ctx context.Context, arg CreateEventTicketParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createEventTicket, arg.WalletID, arg.Reference)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.Amount,
		&i.Currency,
		&i.Type,
		&i.Reference,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createMediaBranch = `-- name: CreateMediaBranch :one
INSERT INTO media_tree (parent_post_id, child_post_id, remix_type)
VALUES ($1, $2, $3)
RETURNING id, parent_post_id, child_post_id, remix_type, metadata, created_at
`

type CreateMediaBranchParams struct {
	ParentPostID pgtype.UUID `json:"parent_post_id"`
	ChildPostID  pgtype.UUID `json:"child_post_id"`
	RemixType    string      `json:"remix_type"`
}

func (q *Queries) CreateMediaBranch(ctx context.Context, arg CreateMediaBranchParams) (MediaTree, error) {
	row := q.db.QueryRow(ctx, createMediaBranch, arg.ParentPostID, arg.ChildPostID, arg.RemixType)
	var i MediaTree
	err := row.Scan(
		&i.ID,
		&i.ParentPostID,
		&i.ChildPostID,
		&i.RemixType,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (buyer_id, total_amount, status)
VALUES ($1, $2, $3)
RETURNING id, buyer_id, total_amount, status, shipping_address, created_at
`

type CreateOrderParams struct {
	BuyerID     pgtype.UUID `json:"buyer_id"`
	TotalAmount int32       `json:"total_amount"`
	Status      string      `json:"status"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder, arg.BuyerID, arg.TotalAmount, arg.Status)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.BuyerID,
		&i.TotalAmount,
		&i.Status,
		&i.ShippingAddress,
		&i.CreatedAt,
	)
	return i, err
}

const createPoll = `-- name: CreatePoll :one
INSERT INTO polls (post_id, question, ends_at) VALUES ($1, $2, $3) RETURNING id, post_id, question, ends_at, created_at
`

type CreatePollParams struct {
	PostID   pgtype.UUID        `json:"post_id"`
	Question string             `json:"question"`
	EndsAt   pgtype.Timestamptz `json:"ends_at"`
}

// 7. Polls
func (q *Queries) CreatePoll(ctx context.Context, arg CreatePollParams) (Poll, error) {
	row := q.db.QueryRow(ctx, createPoll, arg.PostID, arg.Question, arg.EndsAt)
	var i Poll
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.Question,
		&i.EndsAt,
		&i.CreatedAt,
	)
	return i, err
}

const createPollOption = `-- name: CreatePollOption :one
INSERT INTO poll_options (poll_id, option_text) VALUES ($1, $2) RETURNING id, poll_id, option_text
`

type CreatePollOptionParams struct {
	PollID     pgtype.UUID `json:"poll_id"`
	OptionText string      `json:"option_text"`
}

func (q *Queries) CreatePollOption(ctx context.Context, arg CreatePollOptionParams) (PollOption, error) {
	row := q.db.QueryRow(ctx, createPollOption, arg.PollID, arg.OptionText)
	var i PollOption
	err := row.Scan(&i.ID, &i.PollID, &i.OptionText)
	return i, err
}

const createPost = `-- name: CreatePost :one
INSERT INTO posts (author_id, content_text, media_urls, visibility)
VALUES ($1, $2, $3, $4)
RETURNING id, tenant_id, author_id, co_author_id, content_text, media_urls, visibility, is_locked, is_pinned, is_archived, is_draft, location_name, latitude, longitude, content_warning, unlock_price, digital_signature, public_key_id, published_at, created_at, updated_at
`

type CreatePostParams struct {
	AuthorID    pgtype.UUID `json:"author_id"`
	ContentText string      `json:"content_text"`
	MediaUrls   []string    `json:"media_urls"`
	Visibility  string      `json:"visibility"`
}

// 5. Content & Posts
func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, createPost,
		arg.AuthorID,
		arg.ContentText,
		arg.MediaUrls,
		arg.Visibility,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AuthorID,
		&i.CoAuthorID,
		&i.ContentText,
		&i.MediaUrls,
		&i.Visibility,
		&i.IsLocked,
		&i.IsPinned,
		&i.IsArchived,
		&i.IsDraft,
		&i.LocationName,
		&i.Latitude,
		&i.Longitude,
		&i.ContentWarning,
		&i.UnlockPrice,
		&i.DigitalSignature,
		&i.PublicKeyID,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (seller_id, name, description, price, currency, category)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, seller_id, name, description, price, currency, stock_quantity, category, media_urls, is_digital, created_at, updated_at
`

type CreateProductParams struct {
	SellerID    pgtype.UUID `json:"seller_id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	Price       int32       `json:"price"`
	Currency    string      `json:"currency"`
	Category    string      `json:"category"`
}

// 11. Marketplace & Finance
func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.SellerID,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.Currency,
		arg.Category,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.SellerID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Currency,
		&i.StockQuantity,
		&i.Category,
		&i.MediaUrls,
		&i.IsDigital,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (user_id, device_id, ip_address, user_agent, is_ghost_mode)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, device_id, ip_address, latitude, longitude, city, country, user_agent, is_active, is_ghost_mode, last_active_at, created_at
`

type CreateSessionParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	DeviceID    string      `json:"device_id"`
	IpAddress   string      `json:"ip_address"`
	UserAgent   string      `json:"user_agent"`
	IsGhostMode bool        `json:"is_ghost_mode"`
}

// 3. Sessions & Ghost Mode
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.DeviceID,
		arg.IpAddress,
		arg.UserAgent,
		arg.IsGhostMode,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceID,
		&i.IpAddress,
		&i.Latitude,
		&i.Longitude,
		&i.City,
		&i.Country,
		&i.UserAgent,
		&i.IsActive,
		&i.IsGhostMode,
		&i.LastActiveAt,
		&i.CreatedAt,
	)
	return i, err
}

const createStory = `-- name: CreateStory :one
INSERT INTO stories (author_id, media_url, media_type, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, author_id, media_url, media_type, is_archived, expires_at, created_at
`

type CreateStoryParams struct {
	AuthorID  pgtype.UUID        `json:"author_id"`
	MediaUrl  string             `json:"media_url"`
	MediaType string             `json:"media_type"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

// 9. Stories
func (q *Queries) CreateStory(ctx context.Context, arg CreateStoryParams) (Story, error) {
	row := q.db.QueryRow(ctx, createStory,
		arg.AuthorID,
		arg.MediaUrl,
		arg.MediaType,
		arg.ExpiresAt,
	)
	var i Story
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.MediaUrl,
		&i.MediaType,
		&i.IsArchived,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO subscriptions (user_id, plan, active) VALUES ($1, $2, TRUE)
RETURNING id, user_id, plan, started_at, expires_at, active
`

type CreateSubscriptionParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Plan   string      `json:"plan"`
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, createSubscription, arg.UserID, arg.Plan)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Plan,
		&i.StartedAt,
		&i.ExpiresAt,
		&i.Active,
	)
	return i, err
}

const createTenant = `-- name: CreateTenant :one
INSERT INTO tenants (name, domain, custom_config)
VALUES ($1, $2, $3)
RETURNING id, name, domain, custom_config, created_at
`

type CreateTenantParams struct {
	Name         string `json:"name"`
	Domain       string `json:"domain"`
	CustomConfig []byte `json:"custom_config"`
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, createTenant, arg.Name, arg.Domain, arg.CustomConfig)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Domain,
		&i.CustomConfig,
		&i.CreatedAt,
	)
	return i, err
}

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO orders (buyer_id, total_amount, status) VALUES ($1, $2, 'completed')
RETURNING id, buyer_id, total_amount, status, created_at
`

type CreateTransactionParams struct {
	BuyerID     pgtype.UUID `json:"buyer_id"`
	TotalAmount int32       `json:"total_amount"`
}

type CreateTransactionRow struct {
	ID          pgtype.UUID        `json:"id"`
	BuyerID     pgtype.UUID        `json:"buyer_id"`
	TotalAmount int32              `json:"total_amount"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (CreateTransactionRow, error) {
	row := q.db.QueryRow(ctx, createTransaction, arg.BuyerID, arg.TotalAmount)
	var i CreateTransactionRow
	err := row.Scan(
		&i.ID,
		&i.BuyerID,
		&i.TotalAmount,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (tenant_id, username, email, password_hash, avatar_url)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, username, display_name, bio, email, password_hash, avatar_url, is_verified, mfa_enabled, mfa_secret, last_seen_at, is_online, is_private, profile_lock, failed_login_attempts, locked_until, theme_config, created_at, updated_at
`

type CreateUserParams struct {
	TenantID     pgtype.UUID `json:"tenant_id"`
	Username     string      `json:"username"`
	Email        string      `json:"email"`
	PasswordHash string      `json:"password_hash"`
	AvatarUrl    pgtype.Text `json:"avatar_url"`
}

// 2. Identity & Profile
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.TenantID,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.AvatarUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Username,
		&i.DisplayName,
		&i.Bio,
		&i.Email,
		&i.PasswordHash,
		&i.AvatarUrl,
		&i.IsVerified,
		&i.MfaEnabled,
		&i.MfaSecret,
		&i.LastSeenAt,
		&i.IsOnline,
		&i.IsPrivate,
		&i.ProfileLock,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.ThemeConfig,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateSession = `-- name: DeactivateSession :exec
UPDATE sessions SET is_active = FALSE WHERE id = $1 AND user_id = $2
`

type DeactivateSessionParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeactivateSession(ctx context.Context, arg DeactivateSessionParams) error {
	_, err := q.db.Exec(ctx, deactivateSession, arg.ID, arg.UserID)
	return err
}

const endBroadcast = `-- name: EndBroadcast :exec
UPDATE broadcasts SET is_live = FALSE, ended_at = NOW() WHERE id = $1
`

func (q *Queries) EndBroadcast(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, endBroadcast, id)
	return err
}

const findMatch = `-- name: FindMatch :one
SELECT '$2'::uuid as user_b_id, 0.85::float8 as score
`

type FindMatchRow struct {
	UserBID pgtype.UUID `json:"user_b_id"`
	Score   float64     `json:"score"`
}

// 31. Spark Matches
func (q *Queries) FindMatch(ctx context.Context) (FindMatchRow, error) {
	row := q.db.QueryRow(ctx, findMatch)
	var i FindMatchRow
	err := row.Scan(&i.UserBID, &i.Score)
	return i, err
}

const flagSuspiciousAccount = `-- name: FlagSuspiciousAccount :exec
INSERT INTO reports (reporter_id, target_type, target_id, reason, status)
VALUES ('00000000-0000-0000-0000-000000000000', 'user', $1, $2, 'bot_flagged')
ON CONFLICT DO NOTHING
`

type FlagSuspiciousAccountParams struct {
	TargetID pgtype.UUID `json:"target_id"`
	Reason   string      `json:"reason"`
}

func (q *Queries) FlagSuspiciousAccount(ctx context.Context, arg FlagSuspiciousAccountParams) error {
	_, err := q.db.Exec(ctx, flagSuspiciousAccount, arg.TargetID, arg.Reason)
	return err
}

const followUser = `-- name: FollowUser :exec
INSERT INTO follows (follower_id, following_id) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type FollowUserParams struct {
	FollowerID  pgtype.UUID `json:"follower_id"`
	FollowingID pgtype.UUID `json:"following_id"`
}

// 4. Social & Relationships
func (q *Queries) FollowUser(ctx context.Context, arg FollowUserParams) error {
	_, err := q.db.Exec(ctx, followUser, arg.FollowerID, arg.FollowingID)
	return err
}

const getActiveBroadcasts = `-- name: GetActiveBroadcasts :many
SELECT b.id, b.host_id, b.title, b.viewer_count, b.is_live, b.started_at, b.ended_at, b.created_at, u.username as host_username, u.avatar_url as host_avatar
FROM broadcasts b
JOIN users u ON b.host_id = u.id
WHERE b.is_live = TRUE
ORDER BY b.viewer_count DESC
`

type GetActiveBroadcastsRow struct {
	ID           pgtype.UUID        `json:"id"`
	HostID       pgtype.UUID        `json:"host_id"`
	Title        string             `json:"title"`
	ViewerCount  int32              `json:"viewer_count"`
	IsLive       bool               `json:"is_live"`
	StartedAt    pgtype.Timestamptz `json:"started_at"`
	EndedAt      pgtype.Timestamptz `json:"ended_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	HostUsername string             `json:"host_username"`
	HostAvatar   pgtype.Text        `json:"host_avatar"`
}

func (q *Queries) GetActiveBroadcasts(ctx context.Context) ([]GetActiveBroadcastsRow, error) {
	rows, err := q.db.Query(ctx, getActiveBroadcasts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetActiveBroadcastsRow
	for rows.Next() {
		var i GetActiveBroadcastsRow
		if err := rows.Scan(
			&i.ID,
			&i.HostID,
			&i.Title,
			&i.ViewerCount,
			&i.IsLive,
			&i.StartedAt,
			&i.EndedAt,
			&i.CreatedAt,
			&i.HostUsername,
			&i.HostAvatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActiveStories = `-- name: GetActiveStories :many
SELECT s.id, s.author_id, s.media_url, s.media_type, s.is_archived, s.expires_at, s.created_at, u.username as author_username, u.avatar_url as author_avatar
FROM stories s
JOIN users u ON s.author_id = u.id
WHERE s.expires_at > NOW() AND s.is_archived = FALSE
`

type GetActiveStoriesRow struct {
	ID             pgtype.UUID        `json:"id"`
	AuthorID       pgtype.UUID        `json:"author_id"`
	MediaUrl       string             `json:"media_url"`
	MediaType      string             `json:"media_type"`
	IsArchived     bool               `json:"is_archived"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	AuthorUsername string             `json:"author_username"`
	AuthorAvatar   pgtype.Text        `json:"author_avatar"`
}

func (q *Queries) GetActiveStories(ctx context.Context) ([]GetActiveStoriesRow, error) {
	rows, err := q.db.Query(ctx, getActiveStories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetActiveStoriesRow
	for rows.Next() {
		var i GetActiveStoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.MediaUrl,
			&i.MediaType,
			&i.IsArchived,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.AuthorUsername,
			&i.AuthorAvatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChatMessages = `-- name: GetChatMessages :many
SELECT m.id, m.room_id, m.author_id, m.parent_id, m.forwarded_from_id, m.content, m.message_type, m.voice_url, m.is_edited, m.is_pinned, m.is_encrypted, m.version, m.created_at, m.updated_at, u.username as sender_name, u.avatar_url as sender_avatar
FROM chat_messages m
JOIN users u ON m.author_id = u.id
WHERE m.room_id = $1
ORDER BY m.created_at DESC
LIMIT $2 OFFSET $3
`

type GetChatMessagesParams struct {
	RoomID pgtype.UUID `json:"room_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

type GetChatMessagesRow struct {
	ID              pgtype.UUID        `json:"id"`
	RoomID          pgtype.UUID        `json:"room_id"`
	AuthorID        pgtype.UUID        `json:"author_id"`
	ParentID        pgtype.UUID        `json:"parent_id"`
	ForwardedFromID pgtype.UUID        `json:"forwarded_from_id"`
	Content         string             `json:"content"`
	MessageType     string             `json:"message_type"`
	VoiceUrl        pgtype.Text        `json:"voice_url"`
	IsEdited        bool               `json:"is_edited"`
	IsPinned        bool               `json:"is_pinned"`
	IsEncrypted     bool               `json:"is_encrypted"`
	Version         int32              `json:"version"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	SenderName      string             `json:"sender_name"`
	SenderAvatar    pgtype.Text        `json:"sender_avatar"`
}

func (q *Queries) GetChatMessages(ctx context.Context, arg GetChatMessagesParams) ([]GetChatMessagesRow, error) {
	rows, err := q.db.Query(ctx, getChatMessages, arg.RoomID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetChatMessagesRow
	for rows.Next() {
		var i GetChatMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.AuthorID,
			&i.ParentID,
			&i.ForwardedFromID,
			&i.Content,
			&i.MessageType,
			&i.VoiceUrl,
			&i.IsEdited,
			&i.IsPinned,
			&i.IsEncrypted,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SenderName,
			&i.SenderAvatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCircleMembers = `-- name: GetCircleMembers :many
SELECT cm.user_id, u.username, u.display_name, u.avatar_url, cm.role, cm.joined_at
FROM circle_members cm
JOIN users u ON cm.user_id = u.id
WHERE cm.circle_id = $1
`

type GetCircleMembersRow struct {
	UserID      pgtype.UUID        `json:"user_id"`
	Username    string             `json:"username"`
	DisplayName pgtype.Text        `json:"display_name"`
	AvatarUrl   pgtype.Text        `json:"avatar_url"`
	Role        string             `json:"role"`
	JoinedAt    pgtype.Timestamptz `json:"joined_at"`
}

func (q *Queries) GetCircleMembers(ctx context.Context, circleID pgtype.UUID) ([]GetCircleMembersRow, error) {
	rows, err := q.db.Query(ctx, getCircleMembers, circleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCircleMembersRow
	for rows.Next() {
		var i GetCircleMembersRow
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.Role,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCircles = `-- name: GetCircles :many
SELECT id, owner_id, name, is_private, created_at
FROM circles WHERE owner_id = $1 ORDER BY created_at DESC
`

// 25. Circles
func (q *Queries) GetCircles(ctx context.Context, ownerID pgtype.UUID) ([]Circle, error) {
	rows, err := q.db.Query(ctx, getCircles, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Circle
	for rows.Next() {
		var i Circle
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.IsPrivate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCommentsForPost = `-- name: GetCommentsForPost :many
SELECT c.id, c.post_id, c.author_id, c.parent_id, c.content, c.created_at, c.updated_at, u.username as author_username, u.avatar_url as author_avatar
FROM comments c
JOIN users u ON c.author_id = u.id
WHERE c.post_id = $1
ORDER BY c.created_at ASC
`

type GetCommentsForPostRow struct {
	ID             pgtype.UUID        `json:"id"`
	PostID         pgtype.UUID        `json:"post_id"`
	AuthorID       pgtype.UUID        `json:"author_id"`
	ParentID       pgtype.UUID        `json:"parent_id"`
	Content        string             `json:"content"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	AuthorUsername string             `json:"author_username"`
	AuthorAvatar   pgtype.Text        `json:"author_avatar"`
}

func (q *Queries) GetCommentsForPost(ctx context.Context, postID pgtype.UUID) ([]GetCommentsForPostRow, error) {
	rows, err := q.db.Query(ctx, getCommentsForPost, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCommentsForPostRow
	for rows.Next() {
		var i GetCommentsForPostRow
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.AuthorID,
			&i.ParentID,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorUsername,
			&i.AuthorAvatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDeveloperAppByClientID = `-- name: GetDeveloperAppByClientID :one
SELECT id, owner_id, name, client_id, client_secret, redirect_uri, created_at FROM developer_apps WHERE client_id = $1 LIMIT 1
`

func (q *Queries) GetDeveloperAppByClientID(ctx context.Context, clientID string) (DeveloperApp, error) {
	row := q.db.QueryRow(ctx, getDeveloperAppByClientID, clientID)
	var i DeveloperApp
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.ClientID,
		&i.ClientSecret,
		&i.RedirectUri,
		&i.CreatedAt,
	)
	return i, err
}

const getEscrowRecord = `-- name: GetEscrowRecord :one
SELECT id, order_id, buyer_id, seller_id, amount, status, description, release_at, created_at FROM escrow_records WHERE id = $1 LIMIT 1
`

func (q *Queries) GetEscrowRecord(ctx context.Context, id pgtype.UUID) (EscrowRecord, error) {
	row := q.db.QueryRow(ctx, getEscrowRecord, id)
	var i EscrowRecord
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.BuyerID,
		&i.SellerID,
		&i.Amount,
		&i.Status,
		&i.Description,
		&i.ReleaseAt,
		&i.CreatedAt,
	)
	return i, err
}

const getFeatureFlag = `-- name: GetFeatureFlag :one
SELECT is_enabled, rollout_percentage FROM feature_flags WHERE tenant_id = $1 AND key = $2
`

type GetFeatureFlagParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Key      string      `json:"key"`
}

type GetFeatureFlagRow struct {
	IsEnabled         bool  `json:"is_enabled"`
	RolloutPercentage int32 `json:"rollout_percentage"`
}

// 18. Feature Flags
func (q *Queries) GetFeatureFlag(ctx context.Context, arg GetFeatureFlagParams) (GetFeatureFlagRow, error) {
	row := q.db.QueryRow(ctx, getFeatureFlag, arg.TenantID, arg.Key)
	var i GetFeatureFlagRow
	err := row.Scan(&i.IsEnabled, &i.RolloutPercentage)
	return i, err
}

const getFeed = `-- name: GetFeed :many
SELECT p.id, p.tenant_id, p.author_id, p.co_author_id, p.content_text, p.media_urls, p.visibility, p.is_locked, p.is_pinned, p.is_archived, p.is_draft, p.location_name, p.latitude, p.longitude, p.content_warning, p.unlock_price, p.digital_signature, p.public_key_id, p.published_at, p.created_at, p.updated_at, u.username as author_username, u.avatar_url as author_avatar
FROM posts p
JOIN users u ON p.author_id = u.id
WHERE p.published_at <= NOW() AND p.is_archived = FALSE
  AND (p.author_id IN (SELECT f.following_id FROM follows f WHERE f.follower_id = $1 AND f.status = 'accepted') OR p.visibility = 'public')
ORDER BY p.published_at DESC
LIMIT $2 OFFSET $3
`

type GetFeedParams struct {
	FollowerID pgtype.UUID `json:"follower_id"`
	Limit      int32       `json:"limit"`
	Offset     int32       `json:"offset"`
}

type GetFeedRow struct {
	ID               pgtype.UUID        `json:"id"`
	TenantID         pgtype.UUID        `json:"tenant_id"`
	AuthorID         pgtype.UUID        `json:"author_id"`
	CoAuthorID       pgtype.UUID        `json:"co_author_id"`
	ContentText      string             `json:"content_text"`
	MediaUrls        []string           `json:"media_urls"`
	Visibility       string             `json:"visibility"`
	IsLocked         bool               `json:"is_locked"`
	IsPinned         bool               `json:"is_pinned"`
	IsArchived       bool               `json:"is_archived"`
	IsDraft          bool               `json:"is_draft"`
	LocationName     pgtype.Text        `json:"location_name"`
	Latitude         pgtype.Float8      `json:"latitude"`
	Longitude        pgtype.Float8      `json:"longitude"`
	ContentWarning   pgtype.Text        `json:"content_warning"`
	UnlockPrice      pgtype.Int4        `json:"unlock_price"`
	DigitalSignature pgtype.Text        `json:"digital_signature"`
	PublicKeyID      pgtype.Text        `json:"public_key_id"`
	PublishedAt      pgtype.Timestamptz `json:"published_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	AuthorUsername   string             `json:"author_username"`
	AuthorAvatar     pgtype.Text        `json:"author_avatar"`
}

func (q *Queries) GetFeed(ctx context.Context, arg GetFeedParams) ([]GetFeedRow, error) {
	rows, err := q.db.Query(ctx, getFeed, arg.FollowerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFeedRow
	for rows.Next() {
		var i GetFeedRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.AuthorID,
			&i.CoAuthorID,
			&i.ContentText,
			&i.MediaUrls,
			&i.Visibility,
			&i.IsLocked,
			&i.IsPinned,
			&i.IsArchived,
			&i.IsDraft,
			&i.LocationName,
			&i.Latitude,
			&i.Longitude,
			&i.ContentWarning,
			&i.UnlockPrice,
			&i.DigitalSignature,
			&i.PublicKeyID,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorUsername,
			&i.AuthorAvatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFollowRequestsByUser = `-- name: GetFollowRequestsByUser :many
SELECT fr.follower_id, fr.following_id, fr.status, fr.created_at,
       u.username, u.avatar_url, u.display_name
FROM follow_requests fr
JOIN users u ON fr.follower_id = u.id
WHERE fr.following_id = $1 AND fr.status = 'pending'
ORDER BY fr.created_at DESC
`

type GetFollowRequestsByUserRow struct {
	FollowerID  pgtype.UUID        `json:"follower_id"`
	FollowingID pgtype.UUID        `json:"following_id"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	Username    string             `json:"username"`
	AvatarUrl   pgtype.Text        `json:"avatar_url"`
	DisplayName pgtype.Text        `json:"display_name"`
}

func (q *Queries) GetFollowRequestsByUser(ctx context.Context, followingID pgtype.UUID) ([]GetFollowRequestsByUserRow, error) {
	rows, err := q.db.Query(ctx, getFollowRequestsByUser, followingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFollowRequestsByUserRow
	for rows.Next() {
		var i GetFollowRequestsByUserRow
		if err := rows.Scan(
			&i.FollowerID,
			&i.FollowingID,
			&i.Status,
			&i.CreatedAt,
			&i.Username,
			&i.AvatarUrl,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFollowers = `-- name: GetFollowers :many
SELECT u.id, u.tenant_id, u.username, u.display_name, u.bio, u.email, u.password_hash, u.avatar_url, u.is_verified, u.mfa_enabled, u.mfa_secret, u.last_seen_at, u.is_online, u.is_private, u.profile_lock, u.failed_login_attempts, u.locked_until, u.theme_config, u.created_at, u.updated_at FROM users u JOIN follows f ON u.id = f.follower_id WHERE f.following_id = $1
`

func (q *Queries) GetFollowers(ctx context.Context, followingID pgtype.UUID) ([]User, error) {
	rows, err := q.db.Query(ctx, getFollowers, followingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Username,
			&i.DisplayName,
			&i.Bio,
			&i.Email,
			&i.PasswordHash,
			&i.AvatarUrl,
			&i.IsVerified,
			&i.MfaEnabled,
			&i.MfaSecret,
			&i.LastSeenAt,
			&i.IsOnline,
			&i.IsPrivate,
			&i.ProfileLock,
			&i.FailedLoginAttempts,
			&i.LockedUntil,
			&i.ThemeConfig,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFollowing = `-- name: GetFollowing :many
SELECT u.id, u.tenant_id, u.username, u.display_name, u.bio, u.email, u.password_hash, u.avatar_url, u.is_verified, u.mfa_enabled, u.mfa_secret, u.last_seen_at, u.is_online, u.is_private, u.profile_lock, u.failed_login_attempts, u.locked_until, u.theme_config, u.created_at, u.updated_at FROM users u JOIN follows f ON u.id = f.following_id WHERE f.follower_id = $1
`

func (q *Queries) GetFollowing(ctx context.Context, followerID pgtype.UUID) ([]User, error) {
	rows, err := q.db.Query(ctx, getFollowing, followerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Username,
			&i.DisplayName,
			&i.Bio,
			&i.Email,
			&i.PasswordHash,
			&i.AvatarUrl,
			&i.IsVerified,
			&i.MfaEnabled,
			&i.MfaSecret,
			&i.LastSeenAt,
			&i.IsOnline,
			&i.IsPrivate,
			&i.ProfileLock,
			&i.FailedLoginAttempts,
			&i.LockedUntil,
			&i.ThemeConfig,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHashtagTrends = `-- name: GetHashtagTrends :many
SELECT h.tag, COUNT(ph.post_id) as post_count
FROM hashtags h
JOIN post_hashtags ph ON h.id = ph.hashtag_id
JOIN posts p ON ph.post_id = p.id
WHERE p.published_at >= NOW() - INTERVAL '24 hours'
GROUP BY h.tag
ORDER BY post_count DESC
LIMIT $1
`

type GetHashtagTrendsRow struct {
	Tag       string `json:"tag"`
	PostCount int64  `json:"post_count"`
}

// 26. Hashtags
func (q *Queries) GetHashtagTrends(ctx context.Context, limit int32) ([]GetHashtagTrendsRow, error) {
	rows, err := q.db.Query(ctx, getHashtagTrends, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetHashtagTrendsRow
	for rows.Next() {
		var i GetHashtagTrendsRow
		if err := rows.Scan(&i.Tag, &i.PostCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHistory = `-- name: GetHistory :many
SELECT id, user_id, query, created_at
FROM search_history
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type GetHistoryParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
}

func (q *Queries) GetHistory(ctx context.Context, arg GetHistoryParams) ([]SearchHistory, error) {
	rows, err := q.db.Query(ctx, getHistory, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchHistory
	for rows.Next() {
		var i SearchHistory
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Query,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getIdentityKey = `-- name: GetIdentityKey :one
SELECT public_key FROM identity_keys WHERE user_id = $1 AND device_id = $2
`

type GetIdentityKeyParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	DeviceID string      `json:"device_id"`
}

func (q *Queries) GetIdentityKey(ctx context.Context, arg GetIdentityKeyParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getIdentityKey, arg.UserID, arg.DeviceID)
	var public_key []byte
	err := row.Scan(&public_key)
	return public_key, err
}

const getInterests = `-- name: GetInterests :many
SELECT interest FROM search_interests WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) GetInterests(ctx context.Context, userID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, getInterests, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var interest string
		if err := rows.Scan(&interest); err != nil {
			return nil, err
		}
		items = append(items, interest)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMutuals = `-- name: GetMutuals :many
SELECT u.id, u.tenant_id, u.username, u.display_name, u.bio, u.email, u.password_hash, u.avatar_url, u.is_verified, u.mfa_enabled, u.mfa_secret, u.last_seen_at, u.is_online, u.is_private, u.profile_lock, u.failed_login_attempts, u.locked_until, u.theme_config, u.created_at, u.updated_at FROM users u
WHERE u.id IN (SELECT f1.following_id FROM follows f1 WHERE f1.follower_id = $1)
  AND u.id IN (SELECT f2.follower_id FROM follows f2 WHERE f2.following_id = $1)
`

func (q *Queries) GetMutuals(ctx context.Context, followerID pgtype.UUID) ([]User, error) {
	rows, err := q.db.Query(ctx, getMutuals, followerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Username,
			&i.DisplayName,
			&i.Bio,
			&i.Email,
			&i.PasswordHash,
			&i.AvatarUrl,
			&i.IsVerified,
			&i.MfaEnabled,
			&i.MfaSecret,
			&i.LastSeenAt,
			&i.IsOnline,
			&i.IsPrivate,
			&i.ProfileLock,
			&i.FailedLoginAttempts,
			&i.LockedUntil,
			&i.ThemeConfig,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNearbyUsers = `-- name: GetNearbyUsers :many
SELECT u.id, u.username, u.avatar_url, ST_Distance(ul.location, ST_SetSRID(ST_MakePoint($1::float8, $2::float8), 4326)) as distance
FROM user_locations ul
JOIN users u ON ul.user_id = u.id
WHERE ul.is_ghost_mode = FALSE
  AND ST_DWithin(ul.location, ST_SetSRID(ST_MakePoint($1::float8, $2::float8), 4326), $3::float8)
ORDER BY distance ASC
LIMIT $4
`

type GetNearbyUsersParams struct {
	Column1 float64 `json:"column_1"`
	Column2 float64 `json:"column_2"`
	Column3 float64 `json:"column_3"`
	Limit   int32   `json:"limit"`
}

type GetNearbyUsersRow struct {
	ID        pgtype.UUID `json:"id"`
	Username  string      `json:"username"`
	AvatarUrl pgtype.Text `json:"avatar_url"`
	Distance  interface{} `json:"distance"`
}

func (q *Queries) GetNearbyUsers(ctx context.Context, arg GetNearbyUsersParams) ([]GetNearbyUsersRow, error) {
	rows, err := q.db.Query(ctx, getNearbyUsers,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetNearbyUsersRow
	for rows.Next() {
		var i GetNearbyUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.AvatarUrl,
			&i.Distance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingPosts = `-- name: GetPendingPosts :many
SELECT id, tenant_id, author_id, co_author_id, content_text, media_urls, visibility, is_locked, is_pinned, is_archived, is_draft, location_name, latitude, longitude, content_warning, unlock_price, digital_signature, public_key_id, published_at, created_at, updated_at FROM posts WHERE is_draft = TRUE AND published_at <= NOW()
`

// 21. Worker
func (q *Queries) GetPendingPosts(ctx context.Context) ([]Post, error) {
	rows, err := q.db.Query(ctx, getPendingPosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.AuthorID,
			&i.CoAuthorID,
			&i.ContentText,
			&i.MediaUrls,
			&i.Visibility,
			&i.IsLocked,
			&i.IsPinned,
			&i.IsArchived,
			&i.IsDraft,
			&i.LocationName,
			&i.Latitude,
			&i.Longitude,
			&i.ContentWarning,
			&i.UnlockPrice,
			&i.DigitalSignature,
			&i.PublicKeyID,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPollResults = `-- name: GetPollResults :many
SELECT po.option_text, COUNT(pv.user_id) as vote_count
FROM poll_options po
LEFT JOIN poll_votes pv ON po.id = pv.option_id
WHERE po.poll_id = $1
GROUP BY po.id, po.option_text
`

type GetPollResultsRow struct {
	OptionText string `json:"option_text"`
	VoteCount  int64  `json:"vote_count"`
}

func (q *Queries) GetPollResults(ctx context.Context, pollID pgtype.UUID) ([]GetPollResultsRow, error) {
	rows, err := q.db.Query(ctx, getPollResults, pollID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPollResultsRow
	for rows.Next() {
		var i GetPollResultsRow
		if err := rows.Scan(&i.OptionText, &i.VoteCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProduct = `-- name: GetProduct :one
SELECT id, seller_id, name, description, price, currency, stock_quantity, category, media_urls, is_digital, created_at, updated_at FROM products WHERE id = $1 LIMIT 1
`

func (q *Queries) GetProduct(ctx context.Context, id pgtype.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, getProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.SellerID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Currency,
		&i.StockQuantity,
		&i.Category,
		&i.MediaUrls,
		&i.IsDigital,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProfileVisibility = `-- name: GetProfileVisibility :one
SELECT EXISTS (
    SELECT 1 FROM follows WHERE follower_id = $2 AND following_id = $1 AND status = 'accepted'
) OR NOT (SELECT is_private FROM users WHERE id = $1) as is_visible
`

type GetProfileVisibilityParams struct {
	FollowingID pgtype.UUID `json:"following_id"`
	FollowerID  pgtype.UUID `json:"follower_id"`
}

// 19. Privacy
func (q *Queries) GetProfileVisibility(ctx context.Context, arg GetProfileVisibilityParams) (pgtype.Bool, error) {
	row := q.db.QueryRow(ctx, getProfileVisibility, arg.FollowingID, arg.FollowerID)
	var is_visible pgtype.Bool
	err := row.Scan(&is_visible)
	return is_visible, err
}

const getResonanceScore = `-- name: GetResonanceScore :one
SELECT 0.75::float8 as score
`

func (q *Queries) GetResonanceScore(ctx context.Context) (float64, error) {
	row := q.db.QueryRow(ctx, getResonanceScore)
	var score float64
	err := row.Scan(&score)
	return score, err
}

const getSignedPreKey = `-- name: GetSignedPreKey :one
SELECT id, user_id, device_id, key_id, public_key, signature, created_at FROM signed_prekeys WHERE user_id = $1 AND device_id = $2 ORDER BY created_at DESC LIMIT 1
`

type GetSignedPreKeyParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	DeviceID string      `json:"device_id"`
}

func (q *Queries) GetSignedPreKey(ctx context.Context, arg GetSignedPreKeyParams) (SignedPrekey, error) {
	row := q.db.QueryRow(ctx, getSignedPreKey, arg.UserID, arg.DeviceID)
	var i SignedPrekey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceID,
		&i.KeyID,
		&i.PublicKey,
		&i.Signature,
		&i.CreatedAt,
	)
	return i, err
}

const getSuggestedUsers = `-- name: GetSuggestedUsers :many
SELECT u.id, u.username, u.display_name, u.avatar_url, u.bio, u.is_private
FROM users u
WHERE u.id != $1
  AND u.id NOT IN (SELECT following_id FROM follows WHERE follower_id = $1)
  AND u.id NOT IN (SELECT blocked_id FROM blocks WHERE blocker_id = $1)
  AND u.is_private = FALSE
ORDER BY (
  SELECT COUNT(*) FROM follows f1
  JOIN follows f2 ON f1.follower_id = f2.following_id
  WHERE f1.following_id = u.id AND f2.follower_id = $1
) DESC
LIMIT $2
`

type GetSuggestedUsersParams struct {
	ID    pgtype.UUID `json:"id"`
	Limit int32       `json:"limit"`
}

type GetSuggestedUsersRow struct {
	ID          pgtype.UUID `json:"id"`
	Username    string      `json:"username"`
	DisplayName pgtype.Text `json:"display_name"`
	AvatarUrl   pgtype.Text `json:"avatar_url"`
	Bio         pgtype.Text `json:"bio"`
	IsPrivate   bool        `json:"is_private"`
}

// 24. Discovery
func (q *Queries) GetSuggestedUsers(ctx context.Context, arg GetSuggestedUsersParams) ([]GetSuggestedUsersRow, error) {
	rows, err := q.db.Query(ctx, getSuggestedUsers, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSuggestedUsersRow
	for rows.Next() {
		var i GetSuggestedUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.Bio,
			&i.IsPrivate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSuspiciousAccounts = `-- name: GetSuspiciousAccounts :many
SELECT target_id as user_id, reason, created_at as detected_at
FROM reports
WHERE status = 'bot_flagged' AND target_type = 'user'
ORDER BY created_at DESC
`

type GetSuspiciousAccountsRow struct {
	UserID     pgtype.UUID        `json:"user_id"`
	Reason     string             `json:"reason"`
	DetectedAt pgtype.Timestamptz `json:"detected_at"`
}

func (q *Queries) GetSuspiciousAccounts(ctx context.Context) ([]GetSuspiciousAccountsRow, error) {
	rows, err := q.db.Query(ctx, getSuspiciousAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSuspiciousAccountsRow
	for rows.Next() {
		var i GetSuspiciousAccountsRow
		if err := rows.Scan(&i.UserID, &i.Reason, &i.DetectedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTenantByDomain = `-- name: GetTenantByDomain :one

SELECT id, name, domain, custom_config, created_at FROM tenants WHERE domain = $1
`

// Merope Social OS v10.1 Singularity Final Queries
// 1. Multi-Tenancy
func (q *Queries) GetTenantByDomain(ctx context.Context, domain string) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantByDomain, domain)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Domain,
		&i.CustomConfig,
		&i.CreatedAt,
	)
	return i, err
}

const getUnreadCount = `-- name: GetUnreadCount :one
SELECT COUNT(*) FROM notifications WHERE receiver_id = $1 AND is_read = FALSE
`

func (q *Queries) GetUnreadCount(ctx context.Context, receiverID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getUnreadCount, receiverID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUser = `-- name: GetUser :one
SELECT id, tenant_id, username, display_name, bio, email, password_hash, avatar_url, is_verified, mfa_enabled, mfa_secret, last_seen_at, is_online, is_private, profile_lock, failed_login_attempts, locked_until, theme_config, created_at, updated_at FROM users WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Username,
		&i.DisplayName,
		&i.Bio,
		&i.Email,
		&i.PasswordHash,
		&i.AvatarUrl,
		&i.IsVerified,
		&i.MfaEnabled,
		&i.MfaSecret,
		&i.LastSeenAt,
		&i.IsOnline,
		&i.IsPrivate,
		&i.ProfileLock,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.ThemeConfig,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByIdentifier = `-- name: GetUserByIdentifier :one
SELECT id, tenant_id, username, display_name, bio, email, password_hash, avatar_url, is_verified, mfa_enabled, mfa_secret, last_seen_at, is_online, is_private, profile_lock, failed_login_attempts, locked_until, theme_config, created_at, updated_at FROM users WHERE username = $1 OR email = $1 LIMIT 1
`

func (q *Queries) GetUserByIdentifier(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByIdentifier, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Username,
		&i.DisplayName,
		&i.Bio,
		&i.Email,
		&i.PasswordHash,
		&i.AvatarUrl,
		&i.IsVerified,
		&i.MfaEnabled,
		&i.MfaSecret,
		&i.LastSeenAt,
		&i.IsOnline,
		&i.IsPrivate,
		&i.ProfileLock,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.ThemeConfig,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserCircles = `-- name: GetUserCircles :many
SELECT c.id, c.owner_id, c.name, c.is_private, c.created_at
FROM circles c
JOIN circle_members cm ON c.id = cm.circle_id
WHERE cm.user_id = $1
`

func (q *Queries) GetUserCircles(ctx context.Context, userID pgtype.UUID) ([]Circle, error) {
	rows, err := q.db.Query(ctx, getUserCircles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Circle
	for rows.Next() {
		var i Circle
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.IsPrivate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserSessions = `-- name: GetUserSessions :many
SELECT id, user_id, device_id, ip_address, latitude, longitude, city, country, user_agent, is_active, is_ghost_mode, last_active_at, created_at FROM sessions WHERE user_id = $1 AND is_active = TRUE
`

func (q *Queries) GetUserSessions(ctx context.Context, userID pgtype.UUID) ([]Session, error) {
	rows, err := q.db.Query(ctx, getUserSessions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DeviceID,
			&i.IpAddress,
			&i.Latitude,
			&i.Longitude,
			&i.City,
			&i.Country,
			&i.UserAgent,
			&i.IsActive,
			&i.IsGhostMode,
			&i.LastActiveAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserTimeline = `-- name: GetUserTimeline :many
SELECT p.id, p.author_id, p.content_text, p.media_urls, p.visibility,
       p.published_at, p.created_at, u.username, u.avatar_url
FROM posts p
JOIN users u ON p.author_id = u.id
WHERE p.author_id IN (
  SELECT following_id FROM follows WHERE follower_id = $1 AND status = 'accepted'
)
ORDER BY p.published_at DESC
LIMIT $2 OFFSET $3
`

type GetUserTimelineParams struct {
	FollowerID pgtype.UUID `json:"follower_id"`
	Limit      int32       `json:"limit"`
	Offset     int32       `json:"offset"`
}

type GetUserTimelineRow struct {
	ID          pgtype.UUID        `json:"id"`
	AuthorID    pgtype.UUID        `json:"author_id"`
	ContentText string             `json:"content_text"`
	MediaUrls   []string           `json:"media_urls"`
	Visibility  string             `json:"visibility"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	Username    string             `json:"username"`
	AvatarUrl   pgtype.Text        `json:"avatar_url"`
}

// 28. Social Timeline (ScyllaDB fan-out)
func (q *Queries) GetUserTimeline(ctx context.Context, arg GetUserTimelineParams) ([]GetUserTimelineRow, error) {
	rows, err := q.db.Query(ctx, getUserTimeline, arg.FollowerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserTimelineRow
	for rows.Next() {
		var i GetUserTimelineRow
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.ContentText,
			&i.MediaUrls,
			&i.Visibility,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.Username,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserVault = `-- name: GetUserVault :many
SELECT id, user_id, title, encrypted_data, item_type, created_at, updated_at
FROM vault_items WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) GetUserVault(ctx context.Context, userID pgtype.UUID) ([]VaultItem, error) {
	rows, err := q.db.Query(ctx, getUserVault, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VaultItem
	for rows.Next() {
		var i VaultItem
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.EncryptedData,
			&i.ItemType,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWallet = `-- name: GetWallet :one
SELECT user_id, balance, updated_at FROM wallets WHERE user_id = $1
`

func (q *Queries) GetWallet(ctx context.Context, userID pgtype.UUID) (Wallet, error) {
	row := q.db.QueryRow(ctx, getWallet, userID)
	var i Wallet
	err := row.Scan(&i.UserID, &i.Balance, &i.UpdatedAt)
	return i, err
}

const incrementFailedLogin = `-- name: IncrementFailedLogin :exec
UPDATE users SET failed_login_attempts = failed_login_attempts + 1, updated_at = NOW() WHERE id = $1
`

func (q *Queries) IncrementFailedLogin(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, incrementFailedLogin, id)
	return err
}

const isBlocked = `-- name: IsBlocked :one
SELECT EXISTS(SELECT 1 FROM blocks WHERE blocker_id = $1 AND blocked_id = $2)
`

type IsBlockedParams struct {
	BlockerID pgtype.UUID `json:"blocker_id"`
	BlockedID pgtype.UUID `json:"blocked_id"`
}

func (q *Queries) IsBlocked(ctx context.Context, arg IsBlockedParams) (bool, error) {
	row := q.db.QueryRow(ctx, isBlocked, arg.BlockerID, arg.BlockedID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const joinCommunity = `-- name: JoinCommunity :exec
INSERT INTO community_members (community_id, user_id, role) VALUES ($1, $2, $3)
`

type JoinCommunityParams struct {
	CommunityID pgtype.UUID `json:"community_id"`
	UserID      pgtype.UUID `json:"user_id"`
	Role        string      `json:"role"`
}

func (q *Queries) JoinCommunity(ctx context.Context, arg JoinCommunityParams) error {
	_, err := q.db.Exec(ctx, joinCommunity, arg.CommunityID, arg.UserID, arg.Role)
	return err
}

const listBotWebhooks = `-- name: ListBotWebhooks :many
SELECT id, bot_id, callback_url, events, secret_token, created_at FROM bot_webhooks WHERE bot_id = $1
`

func (q *Queries) ListBotWebhooks(ctx context.Context, botID pgtype.UUID) ([]BotWebhook, error) {
	rows, err := q.db.Query(ctx, listBotWebhooks, botID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BotWebhook
	for rows.Next() {
		var i BotWebhook
		if err := rows.Scan(
			&i.ID,
			&i.BotID,
			&i.CallbackUrl,
			&i.Events,
			&i.SecretToken,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAccount = `-- name: LockAccount :exec
UPDATE users SET locked_until = $2, updated_at = NOW() WHERE id = $1
`

type LockAccountParams struct {
	ID          pgtype.UUID        `json:"id"`
	LockedUntil pgtype.Timestamptz `json:"locked_until"`
}

func (q *Queries) LockAccount(ctx context.Context, arg LockAccountParams) error {
	_, err := q.db.Exec(ctx, lockAccount, arg.ID, arg.LockedUntil)
	return err
}

const markNotificationRead = `-- name: MarkNotificationRead :exec
UPDATE notifications SET is_read = TRUE WHERE id = $1 AND receiver_id = $2
`

type MarkNotificationReadParams struct {
	ID         pgtype.UUID `json:"id"`
	ReceiverID pgtype.UUID `json:"receiver_id"`
}

// 27. Notifications
func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) error {
	_, err := q.db.Exec(ctx, markNotificationRead, arg.ID, arg.ReceiverID)
	return err
}

const recordStoryView = `-- name: RecordStoryView :exec
INSERT INTO story_views (story_id, user_id) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type RecordStoryViewParams struct {
	StoryID pgtype.UUID `json:"story_id"`
	UserID  pgtype.UUID `json:"user_id"`
}

func (q *Queries) RecordStoryView(ctx context.Context, arg RecordStoryViewParams) error {
	_, err := q.db.Exec(ctx, recordStoryView, arg.StoryID, arg.UserID)
	return err
}

const resetFailedLogin = `-- name: ResetFailedLogin :exec
UPDATE users SET failed_login_attempts = 0, locked_until = NULL, updated_at = NOW() WHERE id = $1
`

func (q *Queries) ResetFailedLogin(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, resetFailedLogin, id)
	return err
}

const resolveSuspiciousAccount = `-- name: ResolveSuspiciousAccount :exec
UPDATE reports SET status = $2, resolved_at = NOW()
WHERE target_id = $1 AND status = 'bot_flagged' AND target_type = 'user'
`

type ResolveSuspiciousAccountParams struct {
	TargetID pgtype.UUID `json:"target_id"`
	Status   string      `json:"status"`
}

func (q *Queries) ResolveSuspiciousAccount(ctx context.Context, arg ResolveSuspiciousAccountParams) error {
	_, err := q.db.Exec(ctx, resolveSuspiciousAccount, arg.TargetID, arg.Status)
	return err
}

const respondToFollowRequest = `-- name: RespondToFollowRequest :exec
UPDATE follow_requests SET status = $3 WHERE follower_id = $1 AND following_id = $2
`

type RespondToFollowRequestParams struct {
	FollowerID  pgtype.UUID `json:"follower_id"`
	FollowingID pgtype.UUID `json:"following_id"`
	Status      string      `json:"status"`
}

func (q *Queries) RespondToFollowRequest(ctx context.Context, arg RespondToFollowRequestParams) error {
	_, err := q.db.Exec(ctx, respondToFollowRequest, arg.FollowerID, arg.FollowingID, arg.Status)
	return err
}

const rsvpEvent = `-- name: RsvpEvent :exec
INSERT INTO event_attendees (event_id, user_id, status) VALUES ($1, $2, 'going')
ON CONFLICT (event_id, user_id) DO UPDATE SET status = EXCLUDED.status, rsvp_at = NOW()
`

type RsvpEventParams struct {
	EventID pgtype.UUID `json:"event_id"`
	UserID  pgtype.UUID `json:"user_id"`
}

func (q *Queries) RsvpEvent(ctx context.Context, arg RsvpEventParams) error {
	_, err := q.db.Exec(ctx, rsvpEvent, arg.EventID, arg.UserID)
	return err
}

const saveHistory = `-- name: SaveHistory :exec
INSERT INTO search_history (user_id, query) VALUES ($1, $2)
ON CONFLICT (user_id, query) DO UPDATE SET created_at = NOW()
`

type SaveHistoryParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Query  string      `json:"query"`
}

func (q *Queries) SaveHistory(ctx context.Context, arg SaveHistoryParams) error {
	_, err := q.db.Exec(ctx, saveHistory, arg.UserID, arg.Query)
	return err
}

const search = `-- name: Search :many
SELECT 'post' as type, p.id as id, p.content_text as title,
       u.username as subtitle, COUNT(r.id)::float8 as score
FROM posts p
JOIN users u ON p.author_id = u.id
LEFT JOIN reactions r ON r.target_id = p.id
WHERE p.content_text ILIKE '%' || $1 || '%'
  AND p.is_archived = FALSE
GROUP BY p.id, u.username
ORDER BY score DESC
LIMIT $2
`

type SearchParams struct {
	Column1 pgtype.Text `json:"column_1"`
	Limit   int32       `json:"limit"`
}

type SearchRow struct {
	Type     string      `json:"type"`
	ID       pgtype.UUID `json:"id"`
	Title    string      `json:"title"`
	Subtitle string      `json:"subtitle"`
	Score    float64     `json:"score"`
}

// 29. Search
func (q *Queries) Search(ctx context.Context, arg SearchParams) ([]SearchRow, error) {
	rows, err := q.db.Query(ctx, search, arg.Column1, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchRow
	for rows.Next() {
		var i SearchRow
		if err := rows.Scan(
			&i.Type,
			&i.ID,
			&i.Title,
			&i.Subtitle,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchUsers = `-- name: SearchUsers :many
SELECT id, username, display_name, avatar_url,
       CASE
           WHEN COALESCE(is_private, FALSE) = FALSE
                OR id = $2
                OR EXISTS (
                    SELECT 1 FROM follows f
                    WHERE f.follower_id = $2
                      AND f.following_id = users.id
                      AND f.status = 'accepted'
                )
           THEN bio
           ELSE NULL
       END AS bio
FROM users
WHERE (username ILIKE '%' || $1 || '%' OR display_name ILIKE '%' || $1 || '%')
  AND id != $2
  AND NOT EXISTS (
      SELECT 1
      FROM blocks b
      WHERE (b.blocker_id = $2 AND b.blocked_id = users.id)
         OR (b.blocker_id = users.id AND b.blocked_id = $2)
  )
ORDER BY display_name
LIMIT $3
`

type SearchUsersParams struct {
	Column1 pgtype.Text `json:"column_1"`
	ID      pgtype.UUID `json:"id"`
	Limit   int32       `json:"limit"`
}

type SearchUsersRow struct {
	ID          pgtype.UUID `json:"id"`
	Username    string      `json:"username"`
	DisplayName pgtype.Text `json:"display_name"`
	AvatarUrl   pgtype.Text `json:"avatar_url"`
	Bio         pgtype.Text `json:"bio"`
}

func (q *Queries) SearchUsers(ctx context.Context, arg SearchUsersParams) ([]SearchUsersRow, error) {
	rows, err := q.db.Query(ctx, searchUsers, arg.Column1, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchUsersRow
	for rows.Next() {
		var i SearchUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.Bio,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sendFollowRequest = `-- name: SendFollowRequest :exec
INSERT INTO follow_requests (follower_id, following_id, status) VALUES ($1, $2, 'pending')
ON CONFLICT (follower_id, following_id) DO UPDATE SET status = 'pending', created_at = NOW()
`

type SendFollowRequestParams struct {
	FollowerID  pgtype.UUID `json:"follower_id"`
	FollowingID pgtype.UUID `json:"following_id"`
}

// 23. Follow Requests
func (q *Queries) SendFollowRequest(ctx context.Context, arg SendFollowRequestParams) error {
	_, err := q.db.Exec(ctx, sendFollowRequest, arg.FollowerID, arg.FollowingID)
	return err
}

const setGhostMode = `-- name: SetGhostMode :one
UPDATE sessions SET is_ghost_mode = $2 WHERE id = $1 RETURNING id, user_id, device_id, ip_address, latitude, longitude, city, country, user_agent, is_active, is_ghost_mode, last_active_at, created_at
`

type SetGhostModeParams struct {
	ID          pgtype.UUID `json:"id"`
	IsGhostMode bool        `json:"is_ghost_mode"`
}

func (q *Queries) SetGhostMode(ctx context.Context, arg SetGhostModeParams) (Session, error) {
	row := q.db.QueryRow(ctx, setGhostMode, arg.ID, arg.IsGhostMode)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceID,
		&i.IpAddress,
		&i.Latitude,
		&i.Longitude,
		&i.City,
		&i.Country,
		&i.UserAgent,
		&i.IsActive,
		&i.IsGhostMode,
		&i.LastActiveAt,
		&i.CreatedAt,
	)
	return i, err
}

const takeOneTimePreKey = `-- name: TakeOneTimePreKey :one
DELETE FROM onetime_prekeys
WHERE id = (SELECT o.id FROM onetime_prekeys o WHERE o.user_id = $1 AND o.device_id = $2 LIMIT 1)
RETURNING id, user_id, device_id, key_id, public_key, created_at
`

type TakeOneTimePreKeyParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	DeviceID string      `json:"device_id"`
}

func (q *Queries) TakeOneTimePreKey(ctx context.Context, arg TakeOneTimePreKeyParams) (OnetimePrekey, error) {
	row := q.db.QueryRow(ctx, takeOneTimePreKey, arg.UserID, arg.DeviceID)
	var i OnetimePrekey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceID,
		&i.KeyID,
		&i.PublicKey,
		&i.CreatedAt,
	)
	return i, err
}

const unblockUser = `-- name: UnblockUser :exec
DELETE FROM blocks WHERE blocker_id = $1 AND blocked_id = $2
`

type UnblockUserParams struct {
	BlockerID pgtype.UUID `json:"blocker_id"`
	BlockedID pgtype.UUID `json:"blocked_id"`
}

func (q *Queries) UnblockUser(ctx context.Context, arg UnblockUserParams) error {
	_, err := q.db.Exec(ctx, unblockUser, arg.BlockerID, arg.BlockedID)
	return err
}

const unfollowUser = `-- name: UnfollowUser :exec
DELETE FROM follows WHERE follower_id = $1 AND following_id = $2
`

type UnfollowUserParams struct {
	FollowerID  pgtype.UUID `json:"follower_id"`
	FollowingID pgtype.UUID `json:"following_id"`
}

func (q *Queries) UnfollowUser(ctx context.Context, arg UnfollowUserParams) error {
	_, err := q.db.Exec(ctx, unfollowUser, arg.FollowerID, arg.FollowingID)
	return err
}

const updateChatMessage = `-- name: UpdateChatMessage :one
UPDATE chat_messages SET content = $3, is_edited = TRUE, updated_at = NOW()
WHERE id = $1 AND author_id = $2
RETURNING id, room_id, author_id, parent_id, forwarded_from_id, content, message_type, voice_url, is_edited, is_pinned, is_encrypted, version, created_at, updated_at
`

type UpdateChatMessageParams struct {
	ID       pgtype.UUID `json:"id"`
	AuthorID pgtype.UUID `json:"author_id"`
	Content  string      `json:"content"`
}

func (q *Queries) UpdateChatMessage(ctx context.Context, arg UpdateChatMessageParams) (ChatMessage, error) {
	row := q.db.QueryRow(ctx, updateChatMessage, arg.ID, arg.AuthorID, arg.Content)
	var i ChatMessage
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.AuthorID,
		&i.ParentID,
		&i.ForwardedFromID,
		&i.Content,
		&i.MessageType,
		&i.VoiceUrl,
		&i.IsEdited,
		&i.IsPinned,
		&i.IsEncrypted,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateEscrowStatus = `-- name: UpdateEscrowStatus :exec
UPDATE escrow_records SET status = $2 WHERE id = $1
`

type UpdateEscrowStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateEscrowStatus(ctx context.Context, arg UpdateEscrowStatusParams) error {
	_, err := q.db.Exec(ctx, updateEscrowStatus, arg.ID, arg.Status)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users SET username = $2, email = $3, avatar_url = $4, updated_at = NOW()
WHERE id = $1
RETURNING id, tenant_id, username, display_name, bio, email, password_hash, avatar_url, is_verified, mfa_enabled, mfa_secret, last_seen_at, is_online, is_private, profile_lock, failed_login_attempts, locked_until, theme_config, created_at, updated_at
`

type UpdateUserParams struct {
	ID        pgtype.UUID `json:"id"`
	Username  string      `json:"username"`
	Email     string      `json:"email"`
	AvatarUrl pgtype.Text `json:"avatar_url"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Username,
		arg.Email,
		arg.AvatarUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Username,
		&i.DisplayName,
		&i.Bio,
		&i.Email,
		&i.PasswordHash,
		&i.AvatarUrl,
		&i.IsVerified,
		&i.MfaEnabled,
		&i.MfaSecret,
		&i.LastSeenAt,
		&i.IsOnline,
		&i.IsPrivate,
		&i.ProfileLock,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.ThemeConfig,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserLocation = `-- name: UpdateUserLocation :exec
INSERT INTO user_locations (user_id, location, is_ghost_mode, updated_at)
VALUES ($1, ST_SetSRID(ST_MakePoint($2::float8, $3::float8), 4326), $4, NOW())
ON CONFLICT (user_id) DO UPDATE SET
    location = EXCLUDED.location,
    is_ghost_mode = EXCLUDED.is_ghost_mode,
    updated_at = NOW()
`

type UpdateUserLocationParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	Column2     float64     `json:"column_2"`
	Column3     float64     `json:"column_3"`
	IsGhostMode bool        `json:"is_ghost_mode"`
}

// 15. Nearby
func (q *Queries) UpdateUserLocation(ctx context.Context, arg UpdateUserLocationParams) error {
	_, err := q.db.Exec(ctx, updateUserLocation,
		arg.UserID,
		arg.Column2,
		arg.Column3,
		arg.IsGhostMode,
	)
	return err
}

const updateUserMFA = `-- name: UpdateUserMFA :exec
UPDATE users SET mfa_enabled = $2, mfa_secret = $3 WHERE id = $1
`

type UpdateUserMFAParams struct {
	ID         pgtype.UUID `json:"id"`
	MfaEnabled bool        `json:"mfa_enabled"`
	MfaSecret  pgtype.Text `json:"mfa_secret"`
}

func (q *Queries) UpdateUserMFA(ctx context.Context, arg UpdateUserMFAParams) error {
	_, err := q.db.Exec(ctx, updateUserMFA, arg.ID, arg.MfaEnabled, arg.MfaSecret)
	return err
}

const updateWalletBalance = `-- name: UpdateWalletBalance :exec
UPDATE wallets SET balance = balance + $2, updated_at = NOW() WHERE user_id = $1
`

type UpdateWalletBalanceParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	Balance int32       `json:"balance"`
}

func (q *Queries) UpdateWalletBalance(ctx context.Context, arg UpdateWalletBalanceParams) error {
	_, err := q.db.Exec(ctx, updateWalletBalance, arg.UserID, arg.Balance)
	return err
}

const upsertIdentityKey = `-- name: UpsertIdentityKey :exec
INSERT INTO identity_keys (user_id, device_id, public_key)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, device_id) DO UPDATE SET public_key = EXCLUDED.public_key
`

type UpsertIdentityKeyParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	DeviceID  string      `json:"device_id"`
	PublicKey []byte      `json:"public_key"`
}

// 16. E2EE
func (q *Queries) UpsertIdentityKey(ctx context.Context, arg UpsertIdentityKeyParams) error {
	_, err := q.db.Exec(ctx, upsertIdentityKey, arg.UserID, arg.DeviceID, arg.PublicKey)
	return err
}

const upsertOneTimePreKey = `-- name: UpsertOneTimePreKey :exec
INSERT INTO onetime_prekeys (user_id, device_id, key_id, public_key)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, device_id, key_id) DO NOTHING
`

type UpsertOneTimePreKeyParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	DeviceID  string      `json:"device_id"`
	KeyID     int32       `json:"key_id"`
	PublicKey []byte      `json:"public_key"`
}

func (q *Queries) UpsertOneTimePreKey(ctx context.Context, arg UpsertOneTimePreKeyParams) error {
	_, err := q.db.Exec(ctx, upsertOneTimePreKey,
		arg.UserID,
		arg.DeviceID,
		arg.KeyID,
		arg.PublicKey,
	)
	return err
}

const upsertSignedPreKey = `-- name: UpsertSignedPreKey :exec
INSERT INTO signed_prekeys (user_id, device_id, key_id, public_key, signature)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (user_id, device_id, key_id) DO UPDATE SET public_key = EXCLUDED.public_key, signature = EXCLUDED.signature
`

type UpsertSignedPreKeyParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	DeviceID  string      `json:"device_id"`
	KeyID     int32       `json:"key_id"`
	PublicKey []byte      `json:"public_key"`
	Signature []byte      `json:"signature"`
}

func (q *Queries) UpsertSignedPreKey(ctx context.Context, arg UpsertSignedPreKeyParams) error {
	_, err := q.db.Exec(ctx, upsertSignedPreKey,
		arg.UserID,
		arg.DeviceID,
		arg.KeyID,
		arg.PublicKey,
		arg.Signature,
	)
	return err
}

const upsertVideoMetadata = `-- name: UpsertVideoMetadata :one
INSERT INTO video_metadata (post_id, duration_seconds, resolution_width, resolution_height)
VALUES ($1, $2, $3, $4)
ON CONFLICT (post_id) DO UPDATE SET duration_seconds = EXCLUDED.duration_seconds
RETURNING post_id, duration_seconds, resolution_width, resolution_height, encoding_status, is_spatial, spatial_config, bitrate_kbps, frame_rate
`

type UpsertVideoMetadataParams struct {
	PostID           pgtype.UUID `json:"post_id"`
	DurationSeconds  int32       `json:"duration_seconds"`
	ResolutionWidth  pgtype.Int4 `json:"resolution_width"`
	ResolutionHeight pgtype.Int4 `json:"resolution_height"`
}

// 20. Video
func (q *Queries) UpsertVideoMetadata(ctx context.Context, arg UpsertVideoMetadataParams) (VideoMetadatum, error) {
	row := q.db.QueryRow(ctx, upsertVideoMetadata,
		arg.PostID,
		arg.DurationSeconds,
		arg.ResolutionWidth,
		arg.ResolutionHeight,
	)
	var i VideoMetadatum
	err := row.Scan(
		&i.PostID,
		&i.DurationSeconds,
		&i.ResolutionWidth,
		&i.ResolutionHeight,
		&i.EncodingStatus,
		&i.IsSpatial,
		&i.SpatialConfig,
		&i.BitrateKbps,
		&i.FrameRate,
	)
	return i, err
}
