// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddChatMember(ctx context.Context, arg AddChatMemberParams) error
	AddEnergyDrop(ctx context.Context, arg AddEnergyDropParams) (EnergyDrop, error)
	AddInterest(ctx context.Context, arg AddInterestParams) error
	AddOrderItem(ctx context.Context, arg AddOrderItemParams) error
	AddReaction(ctx context.Context, arg AddReactionParams) (Reaction, error)
	// 13. Vault
	AddVaultItem(ctx context.Context, arg AddVaultItemParams) (AddVaultItemRow, error)
	AddVideoHotspot(ctx context.Context, arg AddVideoHotspotParams) (VideoHotspot, error)
	AddVideoTrack(ctx context.Context, arg AddVideoTrackParams) (VideoTrack, error)
	// 22. Blocks
	BlockUser(ctx context.Context, arg BlockUserParams) error
	CastPollVote(ctx context.Context, arg CastPollVoteParams) error
	CreateBotWebhook(ctx context.Context, arg CreateBotWebhookParams) (BotWebhook, error)
	// 30. Lumia Broadcasting
	CreateBroadcast(ctx context.Context, arg CreateBroadcastParams) (CreateBroadcastRow, error)
	CreateChatMessage(ctx context.Context, arg CreateChatMessageParams) (ChatMessage, error)
	// 8. Messaging
	CreateChatRoom(ctx context.Context, arg CreateChatRoomParams) (ChatRoom, error)
	// 6. Comments & Reactions
	CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error)
	// 10. Communities & Events
	CreateCommunity(ctx context.Context, arg CreateCommunityParams) (Community, error)
	// 14. Developer & Apps
	CreateDeveloperApp(ctx context.Context, arg CreateDeveloperAppParams) (DeveloperApp, error)
	// 12. Escrow
	CreateEscrowRecord(ctx context.Context, arg CreateEscrowRecordParams) (EscrowRecord, error)
	CreateEvent(ctx context.Context, arg CreateEventParams) (CommunityProposal, error)
	CreateEventTicket(ctx context.Context, arg CreateEventTicketParams) (Transaction, error)
	CreateMediaBranch(ctx context.Context, arg CreateMediaBranchParams) (MediaTree, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	// 7. Polls
	CreatePoll(ctx context.Context, arg CreatePollParams) (Poll, error)
	CreatePollOption(ctx context.Context, arg CreatePollOptionParams) (PollOption, error)
	// 5. Content & Posts
	CreatePost(ctx context.Context, arg CreatePostParams) (Post, error)
	// 11. Marketplace & Finance
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	// 3. Sessions & Ghost Mode
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	// 9. Stories
	CreateStory(ctx context.Context, arg CreateStoryParams) (Story, error)
	CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error)
	CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (CreateTransactionRow, error)
	// 2. Identity & Profile
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeactivateSession(ctx context.Context, arg DeactivateSessionParams) error
	EndBroadcast(ctx context.Context, id pgtype.UUID) error
	// 31. Spark Matches
	FindMatch(ctx context.Context) (FindMatchRow, error)
	FlagSuspiciousAccount(ctx context.Context, arg FlagSuspiciousAccountParams) error
	// 4. Social & Relationships
	FollowUser(ctx context.Context, arg FollowUserParams) error
	GetActiveBroadcasts(ctx context.Context) ([]GetActiveBroadcastsRow, error)
	GetActiveStories(ctx context.Context) ([]GetActiveStoriesRow, error)
	GetChatMessages(ctx context.Context, arg GetChatMessagesParams) ([]GetChatMessagesRow, error)
	GetCircleMembers(ctx context.Context, circleID pgtype.UUID) ([]GetCircleMembersRow, error)
	// 25. Circles
	GetCircles(ctx context.Context, ownerID pgtype.UUID) ([]Circle, error)
	GetCommentsForPost(ctx context.Context, postID pgtype.UUID) ([]GetCommentsForPostRow, error)
	GetDeveloperAppByClientID(ctx context.Context, clientID string) (DeveloperApp, error)
	GetEscrowRecord(ctx context.Context, id pgtype.UUID) (EscrowRecord, error)
	// 18. Feature Flags
	GetFeatureFlag(ctx context.Context, arg GetFeatureFlagParams) (GetFeatureFlagRow, error)
	GetFeed(ctx context.Context, arg GetFeedParams) ([]GetFeedRow, error)
	GetFollowRequestsByUser(ctx context.Context, followingID pgtype.UUID) ([]GetFollowRequestsByUserRow, error)
	GetFollowers(ctx context.Context, followingID pgtype.UUID) ([]User, error)
	GetFollowing(ctx context.Context, followerID pgtype.UUID) ([]User, error)
	// 26. Hashtags
	GetHashtagTrends(ctx context.Context, limit int32) ([]GetHashtagTrendsRow, error)
	GetHistory(ctx context.Context, arg GetHistoryParams) ([]SearchHistory, error)
	GetIdentityKey(ctx context.Context, arg GetIdentityKeyParams) ([]byte, error)
	GetInterests(ctx context.Context, userID pgtype.UUID) ([]string, error)
	GetMutuals(ctx context.Context, followerID pgtype.UUID) ([]User, error)
	GetNearbyUsers(ctx context.Context, arg GetNearbyUsersParams) ([]GetNearbyUsersRow, error)
	// 21. Worker
	GetPendingPosts(ctx context.Context) ([]Post, error)
	GetPollResults(ctx context.Context, pollID pgtype.UUID) ([]GetPollResultsRow, error)
	GetProduct(ctx context.Context, id pgtype.UUID) (Product, error)
	// 19. Privacy
	GetProfileVisibility(ctx context.Context, arg GetProfileVisibilityParams) (pgtype.Bool, error)
	GetResonanceScore(ctx context.Context) (float64, error)
	GetSignedPreKey(ctx context.Context, arg GetSignedPreKeyParams) (SignedPrekey, error)
	// 24. Discovery
	GetSuggestedUsers(ctx context.Context, arg GetSuggestedUsersParams) ([]GetSuggestedUsersRow, error)
	GetSuspiciousAccounts(ctx context.Context) ([]GetSuspiciousAccountsRow, error)
	// Merope Social OS v10.1 Singularity Final Queries
	// 1. Multi-Tenancy
	GetTenantByDomain(ctx context.Context, domain string) (Tenant, error)
	GetUnreadCount(ctx context.Context, receiverID pgtype.UUID) (int64, error)
	GetUser(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserByIdentifier(ctx context.Context, username string) (User, error)
	GetUserCircles(ctx context.Context, userID pgtype.UUID) ([]Circle, error)
	GetUserSessions(ctx context.Context, userID pgtype.UUID) ([]Session, error)
	// 28. Social Timeline (ScyllaDB fan-out)
	GetUserTimeline(ctx context.Context, arg GetUserTimelineParams) ([]GetUserTimelineRow, error)
	GetUserVault(ctx context.Context, userID pgtype.UUID) ([]VaultItem, error)
	GetWallet(ctx context.Context, userID pgtype.UUID) (Wallet, error)
	IncrementFailedLogin(ctx context.Context, id pgtype.UUID) error
	IsBlocked(ctx context.Context, arg IsBlockedParams) (bool, error)
	JoinCommunity(ctx context.Context, arg JoinCommunityParams) error
	ListBotWebhooks(ctx context.Context, botID pgtype.UUID) ([]BotWebhook, error)
	LockAccount(ctx context.Context, arg LockAccountParams) error
	// 27. Notifications
	MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) error
	RecordStoryView(ctx context.Context, arg RecordStoryViewParams) error
	ResetFailedLogin(ctx context.Context, id pgtype.UUID) error
	ResolveSuspiciousAccount(ctx context.Context, arg ResolveSuspiciousAccountParams) error
	RespondToFollowRequest(ctx context.Context, arg RespondToFollowRequestParams) error
	RsvpEvent(ctx context.Context, arg RsvpEventParams) error
	SaveHistory(ctx context.Context, arg SaveHistoryParams) error
	// 29. Search
	Search(ctx context.Context, arg SearchParams) ([]SearchRow, error)
	SearchUsers(ctx context.Context, arg SearchUsersParams) ([]SearchUsersRow, error)
	// 23. Follow Requests
	SendFollowRequest(ctx context.Context, arg SendFollowRequestParams) error
	SetGhostMode(ctx context.Context, arg SetGhostModeParams) (Session, error)
	TakeOneTimePreKey(ctx context.Context, arg TakeOneTimePreKeyParams) (OnetimePrekey, error)
	UnblockUser(ctx context.Context, arg UnblockUserParams) error
	UnfollowUser(ctx context.Context, arg UnfollowUserParams) error
	UpdateChatMessage(ctx context.Context, arg UpdateChatMessageParams) (ChatMessage, error)
	UpdateEscrowStatus(ctx context.Context, arg UpdateEscrowStatusParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	// 15. Nearby
	UpdateUserLocation(ctx context.Context, arg UpdateUserLocationParams) error
	UpdateUserMFA(ctx context.Context, arg UpdateUserMFAParams) error
	UpdateWalletBalance(ctx context.Context, arg UpdateWalletBalanceParams) error
	// 16. E2EE
	UpsertIdentityKey(ctx context.Context, arg UpsertIdentityKeyParams) error
	UpsertOneTimePreKey(ctx context.Context, arg UpsertOneTimePreKeyParams) error
	UpsertSignedPreKey(ctx context.Context, arg UpsertSignedPreKeyParams) error
	// 20. Video
	UpsertVideoMetadata(ctx context.Context, arg UpsertVideoMetadataParams) (VideoMetadatum, error)
}

var _ Querier = (*Queries)(nil)
