package infra

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/jackc/pgx/v5/pgtype"
	"local/merope/internal/database/db"
	"local/merope/internal/core/util"
	"local/merope/internal/modules/developer/domain"
)

type PostgresDeveloperRepository struct { queries *db.Queries; pool *pgxpool.Pool }
func NewPostgresDeveloperRepository(queries *db.Queries, pool *pgxpool.Pool) *PostgresDeveloperRepository { return &PostgresDeveloperRepository{queries: queries, pool: pool} }

func parseUUID(value string) (pgtype.UUID, error) { var id pgtype.UUID; if err := id.Scan(strings.TrimSpace(value)); err != nil { return id, fmt.Errorf("invalid uuid: %w", err) }; return id, nil }
func nullableTime(t pgtype.Timestamptz) *time.Time { if !t.Valid { return nil }; v := t.Time; return &v }

func (r *PostgresDeveloperRepository) CreateApp(ctx context.Context, app *domain.App) error {
	ownerID, err := parseUUID(app.OwnerID); if err != nil { return err }
	settings, _ := json.Marshal(app.Settings)
	var id pgtype.UUID
	err = r.pool.QueryRow(ctx, `INSERT INTO developer_apps (owner_id,name,description,client_id,client_secret,settings) VALUES ($1,$2,$3,$4,$5,$6) RETURNING id,created_at,updated_at`, ownerID, app.Name, app.Description, app.ClientID, app.ClientSecret, settings).Scan(&id, &app.CreatedAt, &app.UpdatedAt)
	if err != nil { return err }
	app.ID = util.UUIDToString(id)
	return nil
}

func (r *PostgresDeveloperRepository) scanApp(ctx context.Context, row pgxRow) (*domain.App, error) {
	var app domain.App; var id, ownerID pgtype.UUID; var description, redirectURI, iconURL, homepageURL, termsURL, privacyURL pgtype.Text; var settings []byte; var scopes, grantTypes, callbackURLs []string; var createdAt, updatedAt pgtype.Timestamptz
	err := row.Scan(&id,&ownerID,&app.Name,&description,&app.ClientID,&app.ClientSecret,&redirectURI,&scopes,&grantTypes,&app.IsPublic,&app.IsActive,&app.IsVerified,&iconURL,&homepageURL,&termsURL,&privacyURL,&callbackURLs,&settings,&createdAt,&updatedAt)
	if err != nil { return nil, err }
	app.ID=util.UUIDToString(id); app.OwnerID=util.UUIDToString(ownerID); app.Description=description.String; app.RedirectURI=redirectURI.String; app.ClientID=app.ClientID; app.IconURL=iconURL.String; app.HomepageURL=homepageURL.String; app.TermsURL=termsURL.String; app.PrivacyURL=privacyURL.String; app.Scopes=scopes; app.GrantTypes=grantTypes; app.CallbackURLs=callbackURLs; app.CreatedAt=createdAt.Time; app.UpdatedAt=updatedAt.Time
	if len(settings)>0 { _ = json.Unmarshal(settings,&app.Settings) }
	return &app,nil
}

type pgxRow interface{ Scan(...any) error }

func (r *PostgresDeveloperRepository) GetApp(ctx context.Context, appID string) (*domain.App, error) {
	id, err := parseUUID(appID); if err != nil { return nil, err }
	return r.scanApp(ctx, r.pool.QueryRow(ctx, `SELECT id,owner_id,name,description,client_id,client_secret,redirect_uri,scopes,grant_types,is_public,is_active,is_verified,icon_url,homepage_url,terms_url,privacy_url,callback_urls,settings,created_at,updated_at FROM developer_apps WHERE id=$1`, id))
}
func (r *PostgresDeveloperRepository) GetAppsByOwner(ctx context.Context, ownerID string, limit, offset int32) ([]*domain.App,error) {
	uid,err:=parseUUID(ownerID); if err!=nil{return nil,err}; if limit<=0{limit=100}; if offset<0{offset=0}
	rows,err:=r.pool.Query(ctx,`SELECT id,owner_id,name,description,client_id,client_secret,redirect_uri,scopes,grant_types,is_public,is_active,is_verified,icon_url,homepage_url,terms_url,privacy_url,callback_urls,settings,created_at,updated_at FROM developer_apps WHERE owner_id=$1 ORDER BY created_at DESC LIMIT $2 OFFSET $3`,uid,limit,offset); if err!=nil{return nil,err}; defer rows.Close()
	result:=make([]*domain.App,0); for rows.Next(){ app,err:=r.scanApp(ctx,rows); if err!=nil{return nil,err}; app.ClientSecret=""; result=append(result,app) }; return result,rows.Err()
}
func (r *PostgresDeveloperRepository) UpdateApp(ctx context.Context, app *domain.App) error {
	id,err:=parseUUID(app.ID); if err!=nil{return err}; settings,_:=json.Marshal(app.Settings); _,err=r.pool.Exec(ctx,`UPDATE developer_apps SET name=$2,description=$3,redirect_uri=$4,scopes=$5,grant_types=$6,is_public=$7,is_active=$8,icon_url=$9,homepage_url=$10,terms_url=$11,privacy_url=$12,callback_urls=$13,settings=$14,updated_at=NOW() WHERE id=$1`,id,app.Name,app.Description,app.RedirectURI,app.Scopes,app.GrantTypes,app.IsPublic,app.IsActive,app.IconURL,app.HomepageURL,app.TermsURL,app.PrivacyURL,app.CallbackURLs,settings); return err
}
func (r *PostgresDeveloperRepository) DeleteApp(ctx context.Context, appID string) error { id,err:=parseUUID(appID); if err!=nil{return err}; _,err=r.pool.Exec(ctx,`DELETE FROM developer_apps WHERE id=$1`,id); return err }
func (r *PostgresDeveloperRepository) VerifyApp(ctx context.Context, appID string) error { id,err:=parseUUID(appID); if err!=nil{return err}; _,err=r.pool.Exec(ctx,`UPDATE developer_apps SET is_verified=TRUE,updated_at=NOW() WHERE id=$1`,id); return err }

func (r *PostgresDeveloperRepository) CreateAPIKey(ctx context.Context, key *domain.APIKey) error { appID,err:=parseUUID(key.AppID); if err!=nil{return err}; scopes:=key.Scopes; _,err=r.pool.Exec(ctx,`INSERT INTO developer_api_keys(app_id,key_hash,key_prefix,name,description,scopes,rate_limit_rpm,rate_limit_rph,is_active,ip_whitelist,last_used_at,expires_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) RETURNING id`,appID,key.KeyHash,key.KeyPrefix,key.Name,key.Description,scopes,key.RateLimitRPM,key.RateLimitRPH,key.IsActive,key.IPWhitelist,nilTime(key.ExpiresAt),key.ExpiresAt); return err }
func nilTime(t *time.Time) any { if t==nil{return nil}; return *t }
func (r *PostgresDeveloperRepository) GetAPIKey(ctx context.Context, keyID string) (*domain.APIKey,error) { id,err:=parseUUID(keyID); if err!=nil{return nil,err}; return r.scanAPIKey(r.pool.QueryRow(ctx,`SELECT id,app_id,key_hash,key_prefix,name,description,scopes,rate_limit_rpm,rate_limit_rph,is_active,ip_whitelist,last_used_at,expires_at,created_at FROM developer_api_keys WHERE id=$1`,id)) }
func (r *PostgresDeveloperRepository) GetAPIKeyByHash(ctx context.Context, keyHash string) (*domain.APIKey,error) { return r.scanAPIKey(r.pool.QueryRow(ctx,`SELECT id,app_id,key_hash,key_prefix,name,description,scopes,rate_limit_rpm,rate_limit_rph,is_active,ip_whitelist,last_used_at,expires_at,created_at FROM developer_api_keys WHERE key_hash=$1`,keyHash)) }
func (r *PostgresDeveloperRepository) scanAPIKey(row pgxRow)(*domain.APIKey,error){ var k domain.APIKey; var id,appID pgtype.UUID; var lastUsed,expires pgtype.Timestamptz; var createdAt pgtype.Timestamptz; err:=row.Scan(&id,&appID,&k.KeyHash,&k.KeyPrefix,&k.Name,&k.Description,&k.Scopes,&k.RateLimitRPM,&k.RateLimitRPH,&k.IsActive,&k.IPWhitelist,&lastUsed,&expires,&createdAt); if err!=nil{return nil,err}; k.ID=util.UUIDToString(id);k.AppID=util.UUIDToString(appID);k.LastUsedAt=nullableTime(lastUsed);k.ExpiresAt=nullableTime(expires);k.CreatedAt=createdAt.Time;return &k,nil }
func (r *PostgresDeveloperRepository) GetAPIKeysByAppID(ctx context.Context, appID string)([]*domain.APIKey,error){ id,err:=parseUUID(appID);if err!=nil{return nil,err};rows,err:=r.pool.Query(ctx,`SELECT id,app_id,key_hash,key_prefix,name,description,scopes,rate_limit_rpm,rate_limit_rph,is_active,ip_whitelist,last_used_at,expires_at,created_at FROM developer_api_keys WHERE app_id=$1 ORDER BY created_at DESC`,id);if err!=nil{return nil,err};defer rows.Close();out:=make([]*domain.APIKey,0);for rows.Next(){k,err:=r.scanAPIKey(rows);if err!=nil{return nil,err};out=append(out,k)};return out,rows.Err()}
func (r *PostgresDeveloperRepository) UpdateAPIKey(ctx context.Context,key *domain.APIKey)error{id,err:=parseUUID(key.ID);if err!=nil{return err};_,err=r.pool.Exec(ctx,`UPDATE developer_api_keys SET name=$2,description=$3,scopes=$4,rate_limit_rpm=$5,rate_limit_rph=$6,is_active=$7,ip_whitelist=$8,expires_at=$9 WHERE id=$1`,id,key.Name,key.Description,key.Scopes,key.RateLimitRPM,key.RateLimitRPH,key.IsActive,key.IPWhitelist,nilTime(key.ExpiresAt));return err}
func(r *PostgresDeveloperRepository)UpdateAPIKeyUsage(ctx context.Context,keyID string)error{id,err:=parseUUID(keyID);if err!=nil{return err};_,err=r.pool.Exec(ctx,`UPDATE developer_api_keys SET last_used_at=NOW() WHERE id=$1`,id);return err}
func(r *PostgresDeveloperRepository)RevokeAPIKey(ctx context.Context,keyID string)error{id,err:=parseUUID(keyID);if err!=nil{return err};_,err=r.pool.Exec(ctx,`UPDATE developer_api_keys SET is_active=FALSE WHERE id=$1`,id);return err}

func(r *PostgresDeveloperRepository)CreateWebhook(ctx context.Context,w *domain.Webhook)error{appID,err:=parseUUID(w.AppID);if err!=nil{return err};policy,_:=json.Marshal(w.RetryPolicy);var id pgtype.UUID;err=r.pool.QueryRow(ctx,`INSERT INTO developer_webhooks(app_id,name,target_url,secret,events,is_active,retry_policy)VALUES($1,$2,$3,$4,$5,$6,$7)RETURNING id,created_at,updated_at`,appID,w.Name,w.TargetURL,w.Secret,w.Events,w.IsActive,policy).Scan(&id,&w.CreatedAt,&w.UpdatedAt);if err!=nil{return err};w.ID=util.UUIDToString(id);return nil}
func(r *PostgresDeveloperRepository)GetWebhook(ctx context.Context,webhookID string)(*domain.Webhook,error){id,err:=parseUUID(webhookID);if err!=nil{return nil,err};return r.scanWebhook(r.pool.QueryRow(ctx,`SELECT id,app_id,name,target_url,secret,events,is_active,retry_policy,created_at,updated_at FROM developer_webhooks WHERE id=$1`,id))}
func(r *PostgresDeveloperRepository)GetWebhooksByAppID(ctx context.Context,appID string)([]*domain.Webhook,error){id,err:=parseUUID(appID);if err!=nil{return nil,err};rows,err:=r.pool.Query(ctx,`SELECT id,app_id,name,target_url,secret,events,is_active,retry_policy,created_at,updated_at FROM developer_webhooks WHERE app_id=$1 ORDER BY created_at DESC`,id);if err!=nil{return nil,err};defer rows.Close();out:=make([]*domain.Webhook,0);for rows.Next(){w,err:=r.scanWebhook(rows);if err!=nil{return nil,err};out=append(out,w)};return out,rows.Err()}
func(r *PostgresDeveloperRepository)scanWebhook(row pgxRow)(*domain.Webhook,error){var w domain.Webhook;var id,appID pgtype.UUID;var secret string;var events []string;var active bool;var policy []byte;var createdAt,updatedAt pgtype.Timestamptz;err:=row.Scan(&id,&appID,&w.Name,&w.TargetURL,&secret,&events,&active,&policy,&createdAt,&updatedAt);if err!=nil{return nil,err};w.ID=util.UUIDToString(id);w.AppID=util.UUIDToString(appID);w.Secret=secret;w.Events=events;w.IsActive=active;w.CreatedAt=createdAt.Time;w.UpdatedAt=updatedAt.Time;_=json.Unmarshal(policy,&w.RetryPolicy);stats,_:=r.webhookStats(context.Background(),w.ID);w.Stats=*stats;return &w,nil}
func(r *PostgresDeveloperRepository)UpdateWebhook(ctx context.Context,w *domain.Webhook)error{id,err:=parseUUID(w.ID);if err!=nil{return err};policy,_:=json.Marshal(w.RetryPolicy);_,err=r.pool.Exec(ctx,`UPDATE developer_webhooks SET name=$2,target_url=$3,events=$4,is_active=$5,retry_policy=$6,updated_at=NOW() WHERE id=$1`,id,w.Name,w.TargetURL,w.Events,w.IsActive,policy);return err}
func(r *PostgresDeveloperRepository)DeleteWebhook(ctx context.Context,webhookID string)error{id,err:=parseUUID(webhookID);if err!=nil{return err};_,err=r.pool.Exec(ctx,`DELETE FROM developer_webhooks WHERE id=$1`,id);return err}
func(r *PostgresDeveloperRepository)RecordWebhookDelivery(ctx context.Context,webhookID string,success bool,statusCode int,errMsg string)error{id,err:=parseUUID(webhookID);if err!=nil{return err};_,err=r.pool.Exec(ctx,`INSERT INTO developer_webhook_deliveries(webhook_id,status_code,success,error_message)VALUES($1,$2,$3,$4)`,id,statusCode,success,errMsg);return err}
func(r *PostgresDeveloperRepository)webhookStats(ctx context.Context,id string)(*domain.WebhookStats,error){wid,err:=parseUUID(id);if err!=nil{return nil,err};var st domain.WebhookStats;var lastDelivered,lastFailed pgtype.Timestamptz;err=r.pool.QueryRow(ctx,`SELECT COUNT(*)::bigint,COUNT(*) FILTER(WHERE success)::bigint,COUNT(*) FILTER(WHERE NOT success)::bigint,COALESCE(AVG(EXTRACT(EPOCH FROM (delivered_at-LAG(delivered_at) OVER(ORDER BY delivered_at)))*1000),0) FROM developer_webhook_deliveries WHERE webhook_id=$1`,wid).Scan(&st.TotalDeliveries,&st.SuccessCount,&st.FailureCount,&st.AvgResponseTime);if err!=nil{return &st,nil};_ = r.pool.QueryRow(ctx,`SELECT MAX(delivered_at) FILTER(WHERE success),MAX(delivered_at) FILTER(WHERE NOT success) FROM developer_webhook_deliveries WHERE webhook_id=$1`,wid).Scan(&lastDelivered,&lastFailed);st.LastDeliveredAt=nullableTime(lastDelivered);st.LastFailedAt=nullableTime(lastFailed);return &st,nil}
func(r *PostgresDeveloperRepository)GetWebhookStats(ctx context.Context,webhookID string)(*domain.WebhookStats,error){return r.webhookStats(ctx,webhookID)}

func(r *PostgresDeveloperRepository)CreateBot(ctx context.Context,b *domain.Bot)error{appID,err:=parseUUID(b.AppID);if err!=nil{return err};caps,_:=json.Marshal(b.Capabilities);settings,_:=json.Marshal(b.Settings);var id pgtype.UUID;err=r.pool.QueryRow(ctx,`INSERT INTO developer_bots(app_id,name,description,avatar_url,is_public,is_active,is_official,permissions,capabilities,settings)VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)RETURNING id,created_at,updated_at`,appID,b.Name,b.Description,b.AvatarURL,b.IsPublic,b.IsActive,b.IsOfficial,b.Permissions,caps,settings).Scan(&id,&b.CreatedAt,&b.UpdatedAt);if err!=nil{return err};b.ID=util.UUIDToString(id);return nil}
func(r *PostgresDeveloperRepository)GetBot(ctx context.Context,botID string)(*domain.Bot,error){id,err:=parseUUID(botID);if err!=nil{return nil,err};return r.scanBot(r.pool.QueryRow(ctx,`SELECT id,app_id,name,description,avatar_url,is_public,is_active,is_official,permissions,capabilities,settings,created_at,updated_at FROM developer_bots WHERE id=$1`,id))}
func(r *PostgresDeveloperRepository)GetBotsByAppID(ctx context.Context,appID string)([]*domain.Bot,error){id,err:=parseUUID(appID);if err!=nil{return nil,err};rows,err:=r.pool.Query(ctx,`SELECT id,app_id,name,description,avatar_url,is_public,is_active,is_official,permissions,capabilities,settings,created_at,updated_at FROM developer_bots WHERE app_id=$1 ORDER BY created_at DESC`,id);if err!=nil{return nil,err};defer rows.Close();out:=make([]*domain.Bot,0);for rows.Next(){b,err:=r.scanBot(rows);if err!=nil{return nil,err};out=append(out,b)};return out,rows.Err()}
func(r *PostgresDeveloperRepository)scanBot(row pgxRow)(*domain.Bot,error){var b domain.Bot;var id,appID pgtype.UUID;var desc,avatar pgtype.Text;var caps,settings []byte;var createdAt,updatedAt pgtype.Timestamptz;err:=row.Scan(&id,&appID,&b.Name,&desc,&avatar,&b.IsPublic,&b.IsActive,&b.IsOfficial,&b.Permissions,&caps,&settings,&createdAt,&updatedAt);if err!=nil{return nil,err};b.ID=util.UUIDToString(id);b.AppID=util.UUIDToString(appID);b.Description=desc.String;b.AvatarURL=avatar.String;b.CreatedAt=createdAt.Time;b.UpdatedAt=updatedAt.Time;_=json.Unmarshal(caps,&b.Capabilities);_=json.Unmarshal(settings,&b.Settings);return &b,nil}
func(r *PostgresDeveloperRepository)UpdateBot(ctx context.Context,b *domain.Bot)error{id,err:=parseUUID(b.ID);if err!=nil{return err};caps,_:=json.Marshal(b.Capabilities);settings,_:=json.Marshal(b.Settings);_,err=r.pool.Exec(ctx,`UPDATE developer_bots SET name=$2,description=$3,avatar_url=$4,is_public=$5,is_active=$6,is_official=$7,permissions=$8,capabilities=$9,settings=$10,updated_at=NOW() WHERE id=$1`,id,b.Name,b.Description,b.AvatarURL,b.IsPublic,b.IsActive,b.IsOfficial,b.Permissions,caps,settings);return err}
func(r *PostgresDeveloperRepository)DeleteBot(ctx context.Context,botID string)error{id,err:=parseUUID(botID);if err!=nil{return err};_,err=r.pool.Exec(ctx,`DELETE FROM developer_bots WHERE id=$1`,id);return err}

func(r *PostgresDeveloperRepository)RecordAPIRequest(ctx context.Context,appID,endpoint,method string,duration int32,success bool,bandwidth int64,userID string)error{aid,err:=parseUUID(appID);if err!=nil{return err};var uid any=nil;if strings.TrimSpace(userID)!=""{u,e:=parseUUID(userID);if e!=nil{return e};uid=u};_,err=r.pool.Exec(ctx,`INSERT INTO developer_api_requests(app_id,endpoint,method,duration_ms,success,user_id,bandwidth_bytes)VALUES($1,$2,$3,$4,$5,$6,$7)`,aid,endpoint,method,duration,success,uid,bandwidth);return err}
func(r *PostgresDeveloperRepository)GetMetrics(ctx context.Context,appID,period string)(*domain.DeveloperMetrics,error){aid,err:=parseUUID(appID);if err!=nil{return nil,err};since:=time.Now().Add(-24*time.Hour);switch strings.ToLower(period){case "7d","week","weekly":since=time.Now().Add(-7*24*time.Hour);case "30d","month","monthly":since=time.Now().Add(-30*24*time.Hour)};var m domain.DeveloperMetrics;m.AppID=appID;m.Period=period;if err=r.pool.QueryRow(ctx,`SELECT COUNT(*)::bigint,COUNT(*) FILTER(WHERE NOT success)::int,COALESCE(AVG(duration_ms),0),COALESCE(PERCENTILE_CONT(0.95) WITHIN GROUP(ORDER BY duration_ms),0),COALESCE(PERCENTILE_CONT(0.99) WITHIN GROUP(ORDER BY duration_ms),0),COALESCE(AVG(CASE WHEN success THEN 100.0 ELSE 0.0 END),100.0),COUNT(DISTINCT user_id)::int,COALESCE(SUM(bandwidth_bytes),0)::bigint FROM developer_api_requests WHERE app_id=$1 AND created_at >= $2`,aid,since).Scan(&m.APIRequests,&m.Errors,&m.AvgLatency,&m.P95Latency,&m.P99Latency,&m.SuccessRate,&m.UniqueUsers,&m.BandwidthUsed);err!=nil{return nil,err};rows,err:=r.pool.Query(ctx,`SELECT endpoint,method,COUNT(*)::bigint,COALESCE(AVG(duration_ms),0),COALESCE(AVG(CASE WHEN success THEN 0.0 ELSE 1.0 END),0) FROM developer_api_requests WHERE app_id=$1 AND created_at >= $2 GROUP BY endpoint,method ORDER BY COUNT(*) DESC LIMIT 10`,aid,since);if err==nil{defer rows.Close();for rows.Next(){var e domain.EndpointStats;if err:=rows.Scan(&e.Path,&e.Method,&e.RequestCount,&e.AvgLatency,&e.ErrorRate);err!=nil{return nil,err};m.TopEndpoints=append(m.TopEndpoints,e)}};return &m,nil}
