#include "/etc/nats/nats.key"

server {
  host 0.0.0.0
  port 4222

  http_port: 8222

  cluster {
    port: 6222
  }

  jetstream {
    store_dir: /data/jetstream
    max_memory: 1GiB
    max_file_size: 100G
  }

  monitor {
    host: 0.0.0.0
    port: 8222
  }

  accounts {
    MEROPE {
      users = [{user: merope, password: merope_secret}]
      jetstream = yes
    }
  }
}
